//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
    public partial class ContextoRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identificadorTransaccionField;
        
        private System.DateTime fecTransaccionField;
        
        private string codTipoRespuestaField;
        
        private string valDescripcionRespuestaField;
        
        private DetalleRespuesta[] detalleRespuestaField;
        
        private string ipConsumidorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identificadorTransaccion {
            get {
                return this.identificadorTransaccionField;
            }
            set {
                this.identificadorTransaccionField = value;
                this.RaisePropertyChanged("identificadorTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime fecTransaccion {
            get {
                return this.fecTransaccionField;
            }
            set {
                this.fecTransaccionField = value;
                this.RaisePropertyChanged("fecTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codTipoRespuesta {
            get {
                return this.codTipoRespuestaField;
            }
            set {
                this.codTipoRespuestaField = value;
                this.RaisePropertyChanged("codTipoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string valDescripcionRespuesta {
            get {
                return this.valDescripcionRespuestaField;
            }
            set {
                this.valDescripcionRespuestaField = value;
                this.RaisePropertyChanged("valDescripcionRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detalleRespuesta", IsNullable=true, Order=4)]
        public DetalleRespuesta[] detalleRespuesta {
            get {
                return this.detalleRespuestaField;
            }
            set {
                this.detalleRespuestaField = value;
                this.RaisePropertyChanged("detalleRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ipConsumidor {
            get {
                return this.ipConsumidorField;
            }
            set {
                this.ipConsumidorField = value;
                this.RaisePropertyChanged("ipConsumidor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
    public partial class DetalleRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codTipoDetalleRespuestaField;
        
        private string valDescripcionDetalleRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codTipoDetalleRespuesta {
            get {
                return this.codTipoDetalleRespuestaField;
            }
            set {
                this.codTipoDetalleRespuestaField = value;
                this.RaisePropertyChanged("codTipoDetalleRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valDescripcionDetalleRespuesta {
            get {
                return this.valDescripcionDetalleRespuestaField;
            }
            set {
                this.valDescripcionDetalleRespuestaField = value;
                this.RaisePropertyChanged("valDescripcionDetalleRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
    public partial class Inhibitoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valNumeroDocumentoField;
        
        private string valNombreRazonSocialField;
        
        private string fecReferenciaField;
        
        private string codOrigenField;
        
        private string valOrigenField;
        
        private string fecModificacionField;
        
        private string valObservacionField;
        
        private string valCodigoField;
        
        private string codEstadoField;
        
        private string valEstadoField;
        
        private string valTipoDIField;
        
        private string valPrimerApellidoField;
        
        private string valSegundoApellidoField;
        
        private string valTipoClienteField;
        
        private string valSexoField;
        
        private string codTipoClienteField;
        
        private string codSexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string valNumeroDocumento {
            get {
                return this.valNumeroDocumentoField;
            }
            set {
                this.valNumeroDocumentoField = value;
                this.RaisePropertyChanged("valNumeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valNombreRazonSocial {
            get {
                return this.valNombreRazonSocialField;
            }
            set {
                this.valNombreRazonSocialField = value;
                this.RaisePropertyChanged("valNombreRazonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fecReferencia {
            get {
                return this.fecReferenciaField;
            }
            set {
                this.fecReferenciaField = value;
                this.RaisePropertyChanged("fecReferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codOrigen {
            get {
                return this.codOrigenField;
            }
            set {
                this.codOrigenField = value;
                this.RaisePropertyChanged("codOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string valOrigen {
            get {
                return this.valOrigenField;
            }
            set {
                this.valOrigenField = value;
                this.RaisePropertyChanged("valOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fecModificacion {
            get {
                return this.fecModificacionField;
            }
            set {
                this.fecModificacionField = value;
                this.RaisePropertyChanged("fecModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string valObservacion {
            get {
                return this.valObservacionField;
            }
            set {
                this.valObservacionField = value;
                this.RaisePropertyChanged("valObservacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string valCodigo {
            get {
                return this.valCodigoField;
            }
            set {
                this.valCodigoField = value;
                this.RaisePropertyChanged("valCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codEstado {
            get {
                return this.codEstadoField;
            }
            set {
                this.codEstadoField = value;
                this.RaisePropertyChanged("codEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string valEstado {
            get {
                return this.valEstadoField;
            }
            set {
                this.valEstadoField = value;
                this.RaisePropertyChanged("valEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string valTipoDI {
            get {
                return this.valTipoDIField;
            }
            set {
                this.valTipoDIField = value;
                this.RaisePropertyChanged("valTipoDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string valPrimerApellido {
            get {
                return this.valPrimerApellidoField;
            }
            set {
                this.valPrimerApellidoField = value;
                this.RaisePropertyChanged("valPrimerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string valSegundoApellido {
            get {
                return this.valSegundoApellidoField;
            }
            set {
                this.valSegundoApellidoField = value;
                this.RaisePropertyChanged("valSegundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string valTipoCliente {
            get {
                return this.valTipoClienteField;
            }
            set {
                this.valTipoClienteField = value;
                this.RaisePropertyChanged("valTipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string valSexo {
            get {
                return this.valSexoField;
            }
            set {
                this.valSexoField = value;
                this.RaisePropertyChanged("valSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string codTipoCliente {
            get {
                return this.codTipoClienteField;
            }
            set {
                this.codTipoClienteField = value;
                this.RaisePropertyChanged("codTipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string codSexo {
            get {
                return this.codSexoField;
            }
            set {
                this.codSexoField = value;
                this.RaisePropertyChanged("codSexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
    public partial class FiltroInhibitoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valNumeroDocumentoField;
        
        private string codOperacionField;
        
        private string codModoField;
        
        private string valNombreLargoField;
        
        private string valNombreField;
        
        private string codTipoField;
        
        private int valCodigoField;
        
        private bool valCodigoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string valNumeroDocumento {
            get {
                return this.valNumeroDocumentoField;
            }
            set {
                this.valNumeroDocumentoField = value;
                this.RaisePropertyChanged("valNumeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codOperacion {
            get {
                return this.codOperacionField;
            }
            set {
                this.codOperacionField = value;
                this.RaisePropertyChanged("codOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codModo {
            get {
                return this.codModoField;
            }
            set {
                this.codModoField = value;
                this.RaisePropertyChanged("codModo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string valNombreLargo {
            get {
                return this.valNombreLargoField;
            }
            set {
                this.valNombreLargoField = value;
                this.RaisePropertyChanged("valNombreLargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string valNombre {
            get {
                return this.valNombreField;
            }
            set {
                this.valNombreField = value;
                this.RaisePropertyChanged("valNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string codTipo {
            get {
                return this.codTipoField;
            }
            set {
                this.codTipoField = value;
                this.RaisePropertyChanged("codTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int valCodigo {
            get {
                return this.valCodigoField;
            }
            set {
                this.valCodigoField = value;
                this.RaisePropertyChanged("valCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valCodigoSpecified {
            get {
                return this.valCodigoFieldSpecified;
            }
            set {
                this.valCodigoFieldSpecified = value;
                this.RaisePropertyChanged("valCodigoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
    public partial class ContextoTransaccional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identificadorTransaccionalField;
        
        private System.DateTime fecTransaccionField;
        
        private bool fecTransaccionFieldSpecified;
        
        private string codCanalOriginadorField;
        
        private string codProcesoOriginadorField;
        
        private string codFuncionalidadOriginadorField;
        
        private string ipConsumidorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identificadorTransaccional {
            get {
                return this.identificadorTransaccionalField;
            }
            set {
                this.identificadorTransaccionalField = value;
                this.RaisePropertyChanged("identificadorTransaccional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime fecTransaccion {
            get {
                return this.fecTransaccionField;
            }
            set {
                this.fecTransaccionField = value;
                this.RaisePropertyChanged("fecTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecTransaccionSpecified {
            get {
                return this.fecTransaccionFieldSpecified;
            }
            set {
                this.fecTransaccionFieldSpecified = value;
                this.RaisePropertyChanged("fecTransaccionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codCanalOriginador {
            get {
                return this.codCanalOriginadorField;
            }
            set {
                this.codCanalOriginadorField = value;
                this.RaisePropertyChanged("codCanalOriginador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codProcesoOriginador {
            get {
                return this.codProcesoOriginadorField;
            }
            set {
                this.codProcesoOriginadorField = value;
                this.RaisePropertyChanged("codProcesoOriginador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codFuncionalidadOriginador {
            get {
                return this.codFuncionalidadOriginadorField;
            }
            set {
                this.codFuncionalidadOriginadorField = value;
                this.RaisePropertyChanged("codFuncionalidadOriginador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ipConsumidor {
            get {
                return this.ipConsumidorField;
            }
            set {
                this.ipConsumidorField = value;
                this.RaisePropertyChanged("ipConsumidor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/", ConfigurationName="ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias")]
    public interface SrvAplCobisListasInhibitorias {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionB", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta), Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionB", Name="ContextoRespuesta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBResponse OpBuscarListasInhibitoriasOperacionB(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionB", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBResponse> OpBuscarListasInhibitoriasOperacionBAsync(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionQ", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta), Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionQ", Name="ContextoRespuesta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQResponse OpBuscarListasInhibitoriasOperacionQ(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionQ", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQResponse> OpBuscarListasInhibitoriasOperacionQAsync(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionS", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta), Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionS", Name="ContextoRespuesta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSResponse OpBuscarListasInhibitoriasOperacionS(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp.ws/SrvAplCobisLista" +
            "sInhibitorias/OpBuscarListasInhibitoriasOperacionS", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSResponse> OpBuscarListasInhibitoriasOperacionSAsync(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="opBuscarListasInhibitoriasOperacionBSolicitud", WrapperNamespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp", IsWrapped=true)]
    public partial class OpBuscarListasInhibitoriasOperacionBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria;
        
        public OpBuscarListasInhibitoriasOperacionBRequest() {
        }
        
        public OpBuscarListasInhibitoriasOperacionBRequest(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria) {
            this.contextoTransaccional = contextoTransaccional;
            this.filtroInhibitoria = filtroInhibitoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="opBuscarListasInhibitoriasOperacionBRespuesta", WrapperNamespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp", IsWrapped=true)]
    public partial class OpBuscarListasInhibitoriasOperacionBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta contextoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("inhibitoria", Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", IsNullable=true)]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria;
        
        public OpBuscarListasInhibitoriasOperacionBResponse() {
        }
        
        public OpBuscarListasInhibitoriasOperacionBResponse(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta contextoRespuesta, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria) {
            this.contextoRespuesta = contextoRespuesta;
            this.inhibitoria = inhibitoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="opBuscarListasInhibitoriasOperacionQSolicitud", WrapperNamespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp", IsWrapped=true)]
    public partial class OpBuscarListasInhibitoriasOperacionQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria;
        
        public OpBuscarListasInhibitoriasOperacionQRequest() {
        }
        
        public OpBuscarListasInhibitoriasOperacionQRequest(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria) {
            this.contextoTransaccional = contextoTransaccional;
            this.filtroInhibitoria = filtroInhibitoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="opBuscarListasInhibitoriasOperacionQRespuesta", WrapperNamespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp", IsWrapped=true)]
    public partial class OpBuscarListasInhibitoriasOperacionQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta contextoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("inhibitoria", Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", IsNullable=true)]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria;
        
        public OpBuscarListasInhibitoriasOperacionQResponse() {
        }
        
        public OpBuscarListasInhibitoriasOperacionQResponse(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta contextoRespuesta, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria) {
            this.contextoRespuesta = contextoRespuesta;
            this.inhibitoria = inhibitoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="opBuscarListasInhibitoriasOperacionSSolicitud", WrapperNamespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp", IsWrapped=true)]
    public partial class OpBuscarListasInhibitoriasOperacionSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria;
        
        public OpBuscarListasInhibitoriasOperacionSRequest() {
        }
        
        public OpBuscarListasInhibitoriasOperacionSRequest(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria) {
            this.contextoTransaccional = contextoTransaccional;
            this.filtroInhibitoria = filtroInhibitoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="opBuscarListasInhibitoriasOperacionSRespuesta", WrapperNamespace="http://service.srvaplcobislistasinhibitorias.ecobis.cobiscorp", IsWrapped=true)]
    public partial class OpBuscarListasInhibitoriasOperacionSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp")]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta contextoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("inhibitoria", Namespace="http://dto.srvaplcobisentidades.ecobis.cobiscorp", IsNullable=true)]
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria;
        
        public OpBuscarListasInhibitoriasOperacionSResponse() {
        }
        
        public OpBuscarListasInhibitoriasOperacionSResponse(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta contextoRespuesta, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria) {
            this.contextoRespuesta = contextoRespuesta;
            this.inhibitoria = inhibitoria;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SrvAplCobisListasInhibitoriasChannel : BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvAplCobisListasInhibitoriasClient : System.ServiceModel.ClientBase<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias>, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias {
        
        public SrvAplCobisListasInhibitoriasClient() {
        }
        
        public SrvAplCobisListasInhibitoriasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvAplCobisListasInhibitoriasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvAplCobisListasInhibitoriasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvAplCobisListasInhibitoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBResponse BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionB(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBRequest request) {
            return base.Channel.OpBuscarListasInhibitoriasOperacionB(request);
        }
        
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta OpBuscarListasInhibitoriasOperacionB(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria, out BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria) {
            BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBRequest inValue = new BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBRequest();
            inValue.contextoTransaccional = contextoTransaccional;
            inValue.filtroInhibitoria = filtroInhibitoria;
            BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBResponse retVal = ((BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias)(this)).OpBuscarListasInhibitoriasOperacionB(inValue);
            inhibitoria = retVal.inhibitoria;
            return retVal.contextoRespuesta;
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBResponse> OpBuscarListasInhibitoriasOperacionBAsync(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionBRequest request) {
            return base.Channel.OpBuscarListasInhibitoriasOperacionBAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQResponse BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQ(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQRequest request) {
            return base.Channel.OpBuscarListasInhibitoriasOperacionQ(request);
        }
        
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta OpBuscarListasInhibitoriasOperacionQ(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria, out BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria) {
            BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQRequest inValue = new BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQRequest();
            inValue.contextoTransaccional = contextoTransaccional;
            inValue.filtroInhibitoria = filtroInhibitoria;
            BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQResponse retVal = ((BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias)(this)).OpBuscarListasInhibitoriasOperacionQ(inValue);
            inhibitoria = retVal.inhibitoria;
            return retVal.contextoRespuesta;
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQResponse> OpBuscarListasInhibitoriasOperacionQAsync(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionQRequest request) {
            return base.Channel.OpBuscarListasInhibitoriasOperacionQAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSResponse BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionS(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSRequest request) {
            return base.Channel.OpBuscarListasInhibitoriasOperacionS(request);
        }
        
        public BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoRespuesta OpBuscarListasInhibitoriasOperacionS(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.ContextoTransaccional contextoTransaccional, BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.FiltroInhibitoria filtroInhibitoria, out BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.Inhibitoria[] inhibitoria) {
            BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSRequest inValue = new BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSRequest();
            inValue.contextoTransaccional = contextoTransaccional;
            inValue.filtroInhibitoria = filtroInhibitoria;
            BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSResponse retVal = ((BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.SrvAplCobisListasInhibitorias)(this)).OpBuscarListasInhibitoriasOperacionS(inValue);
            inhibitoria = retVal.inhibitoria;
            return retVal.contextoRespuesta;
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSResponse> OpBuscarListasInhibitoriasOperacionSAsync(BancaSeguros.Aplicacion.ServicioCobisListasInhibitorias.OpBuscarListasInhibitoriasOperacionSRequest request) {
            return base.Channel.OpBuscarListasInhibitoriasOperacionSAsync(request);
        }
    }
}
