//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSegurosUI.ServicioAdministracion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAdministracion.IServicioAdministracion")]
    public interface IServicioAdministracion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/PrevisualizarPlantilla", ReplyAction="http://tempuri.org/IServicioAdministracion/PrevisualizarPlantillaResponse")]
        BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza PrevisualizarPlantilla(BancaSeguros.Entidades.Administracion.EntradaPrevisualizacionDocumentoPoliza entradaPrevisualizacionDocumentoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/PrevisualizarPlantilla", ReplyAction="http://tempuri.org/IServicioAdministracion/PrevisualizarPlantillaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza> PrevisualizarPlantillaAsync(BancaSeguros.Entidades.Administracion.EntradaPrevisualizacionDocumentoPoliza entradaPrevisualizacionDocumentoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarDocumentoPlantillaSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarDocumentoPlantillaSeguroRespon" +
            "se")]
        BancaSeguros.Entidades.General.Resultado InsertarDocumentoPlantillaSeguro(BancaSeguros.Entidades.Seguro.DocumentoPoliza documentoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarDocumentoPlantillaSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarDocumentoPlantillaSeguroRespon" +
            "se")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarDocumentoPlantillaSeguroAsync(BancaSeguros.Entidades.Seguro.DocumentoPoliza documentoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerPlantillasPorIdSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerPlantillasPorIdSeguroResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza> ObtenerPlantillasPorIdSeguro(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerPlantillasPorIdSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerPlantillasPorIdSeguroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza>> ObtenerPlantillasPorIdSeguroAsync(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarPlantilla", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarPlantillaResponse")]
        BancaSeguros.Entidades.General.Resultado EliminarPlantilla(int idDocumentoPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarPlantilla", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarPlantillaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarPlantillaAsync(int idDocumentoPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActivarEstadoPlantilla", ReplyAction="http://tempuri.org/IServicioAdministracion/ActivarEstadoPlantillaResponse")]
        BancaSeguros.Entidades.General.Resultado ActivarEstadoPlantilla(int idDocumentoPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActivarEstadoPlantilla", ReplyAction="http://tempuri.org/IServicioAdministracion/ActivarEstadoPlantillaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActivarEstadoPlantillaAsync(int idDocumentoPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerDocumentoPolizaPorIdDocumentoPo" +
            "liza", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerDocumentoPolizaPorIdDocumentoPo" +
            "lizaResponse")]
        BancaSeguros.Entidades.Seguro.DocumentoPoliza ObtenerDocumentoPolizaPorIdDocumentoPoliza(int idDocumentoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerDocumentoPolizaPorIdDocumentoPo" +
            "liza", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerDocumentoPolizaPorIdDocumentoPo" +
            "lizaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Seguro.DocumentoPoliza> ObtenerDocumentoPolizaPorIdDocumentoPolizaAsync(int idDocumentoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarPlantillasActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarPlantillasActivasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza> ConsultarPlantillasActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarPlantillasActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarPlantillasActivasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza>> ConsultarPlantillasActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarCanalVenta", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarCanalVentaResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarCanalVenta(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarCanalVenta", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarCanalVentaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarCanalVentaAsync(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizaCanalVentaPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizaCanalVentaPorIdResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizaCanalVentaPorId(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizaCanalVentaPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizaCanalVentaPorIdResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizaCanalVentaPorIdAsync(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAseguradoras", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAseguradorasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradoras(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAseguradoras", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAseguradorasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora>> ConsultarAseguradorasAsync(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAseguradoraPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAseguradoraPorIdResponse")]
        BancaSeguros.Entidades.Seguro.Aseguradora ConsultarAseguradoraPorId(int idAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAseguradoraPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAseguradoraPorIdResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradoraPorIdAsync(int idAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarAseguradoraResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarAseguradora(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarAseguradoraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarAseguradoraAsync(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarAseguradoraResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarAseguradora(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarAseguradoraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarAseguradoraAsync(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarConveniosPorIdAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarConveniosPorIdAseguradoraResp" +
            "onse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Convenio> ConsultarConveniosPorIdAseguradora(int idAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarConveniosPorIdAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarConveniosPorIdAseguradoraResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Convenio>> ConsultarConveniosPorIdAseguradoraAsync(int idAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarTipoDocumentoSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarTipoDocumentoSeguroResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarTipoDocumentoSeguro(int idSeguro, int idTipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarTipoDocumentoSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarTipoDocumentoSeguroResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarTipoDocumentoSeguroAsync(int idSeguro, int idTipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarTipoDocumentoSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarTipoDocumentoSeguroResponse")]
        BancaSeguros.Entidades.General.Resultado EliminarTipoDocumentoSeguro(int idSeguro, int idTipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarTipoDocumentoSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarTipoDocumentoSeguroResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarTipoDocumentoSeguroAsync(int idSeguro, int idTipoIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarParametro", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarParametroResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarParametro(BancaSeguros.Entidades.Catalogo.Parametro parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarParametro", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarParametroResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarParametroAsync(BancaSeguros.Entidades.Catalogo.Parametro parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizaParametroPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizaParametroPorIdResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizaParametroPorId(BancaSeguros.Entidades.Catalogo.Parametro parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizaParametroPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizaParametroPorIdResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizaParametroPorIdAsync(BancaSeguros.Entidades.Catalogo.Parametro parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarSeguroResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarSeguro(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarSeguro", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarSeguroResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarSeguroAsync(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerCanalesVentaActivos", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerCanalesVentaActivosResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CanalVenta> ObtenerCanalesVentaActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerCanalesVentaActivos", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerCanalesVentaActivosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CanalVenta>> ObtenerCanalesVentaActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerPeriodicidadesActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerPeriodicidadesActivasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Periodicidad> ObtenerPeriodicidadesActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerPeriodicidadesActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerPeriodicidadesActivasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Periodicidad>> ObtenerPeriodicidadesActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarTodosLosSeguros", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarTodosLosSegurosResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarTodosLosSeguros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarTodosLosSeguros", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarTodosLosSegurosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarTodosLosSegurosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarSeguroPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarSeguroPorIdResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarSeguroPorId(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarSeguroPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarSeguroPorIdResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarSeguroPorIdAsync(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarInformacionSeguroPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarInformacionSeguroPorIdRespons" +
            "e")]
        BancaSeguros.Entidades.Administracion.ParametrizacionSeguro ConsultarInformacionSeguroPorId(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarInformacionSeguroPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarInformacionSeguroPorIdRespons" +
            "e")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Administracion.ParametrizacionSeguro> ConsultarInformacionSeguroPorIdAsync(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorParametros", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorParametrosResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarSegurosPorParametros(string nombreProducto, int codigoProducto, string nombreAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorParametros", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorParametrosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarSegurosPorParametrosAsync(string nombreProducto, int codigoProducto, string nombreAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorAseguradoraResponse" +
            "")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarSegurosPorAseguradora(int idAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorAseguradora", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarSegurosPorAseguradoraResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarSegurosPorAseguradoraAsync(int idAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarIPC", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarIPCResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarIPC(BancaSeguros.Entidades.Catalogo.IPC ipc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarIPC", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarIPCResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarIPCAsync(BancaSeguros.Entidades.Catalogo.IPC ipc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizaIPC", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizaIPCResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizaIPC(BancaSeguros.Entidades.Catalogo.IPC ipc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizaIPC", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizaIPCResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizaIPCAsync(BancaSeguros.Entidades.Catalogo.IPC ipc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarIPC", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarIPCResponse")]
        BancaSeguros.Entidades.Catalogo.IPC ConsultarIPC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarIPC", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarIPCResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Catalogo.IPC> ConsultarIPCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerAuditorias", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerAuditoriasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.General.Auditoria> ObtenerAuditorias(BancaSeguros.Entidades.General.Auditoria auditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ObtenerAuditorias", ReplyAction="http://tempuri.org/IServicioAdministracion/ObtenerAuditoriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.General.Auditoria>> ObtenerAuditoriasAsync(BancaSeguros.Entidades.General.Auditoria auditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarNovedadResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarNovedad(BancaSeguros.Entidades.Catalogo.Novedad novedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarNovedadResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarNovedadAsync(BancaSeguros.Entidades.Catalogo.Novedad novedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarNovedadResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarNovedad(BancaSeguros.Entidades.Catalogo.Novedad novedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarNovedadResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarNovedadAsync(BancaSeguros.Entidades.Catalogo.Novedad novedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarNovedades", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarNovedadesResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Novedad> ConsultarNovedades(BancaSeguros.Entidades.Catalogo.Novedad novedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarNovedades", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarNovedadesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Novedad>> ConsultarNovedadesAsync(BancaSeguros.Entidades.Catalogo.Novedad novedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarCausalNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarCausalNovedadResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarCausalNovedad(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarCausalNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarCausalNovedadResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarCausalNovedadAsync(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarCausalNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarCausalNovedadResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarCausalNovedad(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarCausalNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarCausalNovedadResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarCausalNovedadAsync(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarCausalNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarCausalNovedadResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CausalNovedad> ConsultarCausalNovedad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarCausalNovedad", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarCausalNovedadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CausalNovedad>> ConsultarCausalNovedadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarMensaje", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarMensajeResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarMensaje(BancaSeguros.Entidades.General.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarMensaje", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarMensajeResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarMensajeAsync(BancaSeguros.Entidades.General.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarMensaje", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarMensajeResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarMensaje(BancaSeguros.Entidades.General.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarMensaje", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarMensajeResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarMensajeAsync(BancaSeguros.Entidades.General.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarMensajes", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarMensajesResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.General.Mensaje> ConsultarMensajes(BancaSeguros.Entidades.General.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarMensajes", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarMensajesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.General.Mensaje>> ConsultarMensajesAsync(BancaSeguros.Entidades.General.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarAprobacionDual", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarAprobacionDualResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarAprobacionDual(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarAprobacionDual", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarAprobacionDualResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarAprobacionDualAsync(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDual", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDualRespon" +
            "se")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Administracion.AprobacionDual> ConsultarAprobacionesControlDual(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDual", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDualRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Administracion.AprobacionDual>> ConsultarAprobacionesControlDualAsync(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarAprobacionDual", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarAprobacionDualResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarAprobacionDual(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarAprobacionDual", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarAprobacionDualResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarAprobacionDualAsync(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDualPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDualPorIdR" +
            "esponse")]
        BancaSeguros.Entidades.Administracion.AprobacionDual ConsultarAprobacionesControlDualPorId(int idAprobacionDual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDualPorId", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAprobacionesControlDualPorIdR" +
            "esponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Administracion.AprobacionDual> ConsultarAprobacionesControlDualPorIdAsync(int idAprobacionDual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarVariableProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarVariableProductoResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarVariableProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarVariableProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarVariableProductoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarVariableProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarVariableProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarVariableProductoResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarVariableProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarVariableProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarVariableProductoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarVariableProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProductoResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto> ConsultarVariablesProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto>> ConsultarVariablesProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProductoActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProductoActivasRespo" +
            "nse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto> ConsultarVariablesProductoActivas(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProductoActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarVariablesProductoActivasRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto>> ConsultarVariablesProductoActivasAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarVariableProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarVariableProductoResponse")]
        BancaSeguros.Entidades.General.Resultado EliminarVariableProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarVariableProducto", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarVariableProductoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarVariableProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarMaestraResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarMaestra(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarMaestraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarMaestraAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarMaestraResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarMaestra(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarMaestraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarMaestraAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarMaestras", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarMaestrasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Maestra> ConsultarMaestras(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarMaestras", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarMaestrasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Maestra>> ConsultarMaestrasAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarMaestraResponse")]
        BancaSeguros.Entidades.General.Resultado EliminarMaestra(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarMaestraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarMaestraAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarItemMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarItemMaestraResponse")]
        BancaSeguros.Entidades.General.Resultado InsertarItemMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/InsertarItemMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/InsertarItemMaestraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarItemMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarItemMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarItemMaestraResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarItemMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarItemMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarItemMaestraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarItemMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarItemsMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarItemsMaestraResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.ItemMaestra> ConsultarItemsMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarItemsMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarItemsMaestraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.ItemMaestra>> ConsultarItemsMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarItemMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarItemMaestraResponse")]
        BancaSeguros.Entidades.General.Resultado EliminarItemMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarItemMaestra", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarItemMaestraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarItemMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAseguradorasActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAseguradorasActivasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradorasActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarAseguradorasActivas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarAseguradorasActivasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora>> ConsultarAseguradorasActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarPolizas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarPolizasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposPoliza> ConsultarPolizas(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarPolizas", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarPolizasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposPoliza>> ConsultarPolizasAsync(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarCobros", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarCobrosResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCobros> ConsultarCobros(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarCobros", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarCobrosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCobros>> ConsultarCobrosAsync(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarCancelaciones", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarCancelacionesResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones> ConsultarCancelaciones(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarCancelaciones", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarCancelacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones>> ConsultarCancelacionesAsync(int opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarFiltrosCancelaciones", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarFiltrosCancelacionesResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones> ConsultarFiltrosCancelaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarFiltrosCancelaciones", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarFiltrosCancelacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones>> ConsultarFiltrosCancelacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarDatosArchivoPlano", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarDatosArchivoPlanoResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarDatosArchivoPlano(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/GuardarDatosArchivoPlano", ReplyAction="http://tempuri.org/IServicioAdministracion/GuardarDatosArchivoPlanoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarDatosArchivoPlanoAsync(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarDatosGrilla", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarDatosGrillaResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Planos.ArchivoPlano> ConsultarDatosGrilla();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ConsultarDatosGrilla", ReplyAction="http://tempuri.org/IServicioAdministracion/ConsultarDatosGrillaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.ArchivoPlano>> ConsultarDatosGrillaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarDatosArchivoPlano", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarDatosArchivoPlanoResponse")]
        BancaSeguros.Entidades.General.Resultado ActualizarDatosArchivoPlano(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/ActualizarDatosArchivoPlano", ReplyAction="http://tempuri.org/IServicioAdministracion/ActualizarDatosArchivoPlanoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarDatosArchivoPlanoAsync(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarDatosArchivoPlano", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarDatosArchivoPlanoResponse")]
        BancaSeguros.Entidades.General.Resultado EliminarDatosArchivoPlano(int idProgramacion, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAdministracion/EliminarDatosArchivoPlano", ReplyAction="http://tempuri.org/IServicioAdministracion/EliminarDatosArchivoPlanoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarDatosArchivoPlanoAsync(int idProgramacion, string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAdministracionChannel : BancaSegurosUI.ServicioAdministracion.IServicioAdministracion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAdministracionClient : System.ServiceModel.ClientBase<BancaSegurosUI.ServicioAdministracion.IServicioAdministracion>, BancaSegurosUI.ServicioAdministracion.IServicioAdministracion {
        
        public ServicioAdministracionClient() {
        }
        
        public ServicioAdministracionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAdministracionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAdministracionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAdministracionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza PrevisualizarPlantilla(BancaSeguros.Entidades.Administracion.EntradaPrevisualizacionDocumentoPoliza entradaPrevisualizacionDocumentoPoliza) {
            return base.Channel.PrevisualizarPlantilla(entradaPrevisualizacionDocumentoPoliza);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza> PrevisualizarPlantillaAsync(BancaSeguros.Entidades.Administracion.EntradaPrevisualizacionDocumentoPoliza entradaPrevisualizacionDocumentoPoliza) {
            return base.Channel.PrevisualizarPlantillaAsync(entradaPrevisualizacionDocumentoPoliza);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarDocumentoPlantillaSeguro(BancaSeguros.Entidades.Seguro.DocumentoPoliza documentoPoliza) {
            return base.Channel.InsertarDocumentoPlantillaSeguro(documentoPoliza);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarDocumentoPlantillaSeguroAsync(BancaSeguros.Entidades.Seguro.DocumentoPoliza documentoPoliza) {
            return base.Channel.InsertarDocumentoPlantillaSeguroAsync(documentoPoliza);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza> ObtenerPlantillasPorIdSeguro(int idSeguro) {
            return base.Channel.ObtenerPlantillasPorIdSeguro(idSeguro);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza>> ObtenerPlantillasPorIdSeguroAsync(int idSeguro) {
            return base.Channel.ObtenerPlantillasPorIdSeguroAsync(idSeguro);
        }
        
        public BancaSeguros.Entidades.General.Resultado EliminarPlantilla(int idDocumentoPlantilla) {
            return base.Channel.EliminarPlantilla(idDocumentoPlantilla);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarPlantillaAsync(int idDocumentoPlantilla) {
            return base.Channel.EliminarPlantillaAsync(idDocumentoPlantilla);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActivarEstadoPlantilla(int idDocumentoPlantilla) {
            return base.Channel.ActivarEstadoPlantilla(idDocumentoPlantilla);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActivarEstadoPlantillaAsync(int idDocumentoPlantilla) {
            return base.Channel.ActivarEstadoPlantillaAsync(idDocumentoPlantilla);
        }
        
        public BancaSeguros.Entidades.Seguro.DocumentoPoliza ObtenerDocumentoPolizaPorIdDocumentoPoliza(int idDocumentoPoliza) {
            return base.Channel.ObtenerDocumentoPolizaPorIdDocumentoPoliza(idDocumentoPoliza);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Seguro.DocumentoPoliza> ObtenerDocumentoPolizaPorIdDocumentoPolizaAsync(int idDocumentoPoliza) {
            return base.Channel.ObtenerDocumentoPolizaPorIdDocumentoPolizaAsync(idDocumentoPoliza);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza> ConsultarPlantillasActivas() {
            return base.Channel.ConsultarPlantillasActivas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.DocumentoPoliza>> ConsultarPlantillasActivasAsync() {
            return base.Channel.ConsultarPlantillasActivasAsync();
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarCanalVenta(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta) {
            return base.Channel.GuardarCanalVenta(canalVenta);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarCanalVentaAsync(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta) {
            return base.Channel.GuardarCanalVentaAsync(canalVenta);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizaCanalVentaPorId(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta) {
            return base.Channel.ActualizaCanalVentaPorId(canalVenta);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizaCanalVentaPorIdAsync(BancaSeguros.Entidades.Catalogo.CanalVenta canalVenta) {
            return base.Channel.ActualizaCanalVentaPorIdAsync(canalVenta);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradoras(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora) {
            return base.Channel.ConsultarAseguradoras(aseguradora);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora>> ConsultarAseguradorasAsync(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora) {
            return base.Channel.ConsultarAseguradorasAsync(aseguradora);
        }
        
        public BancaSeguros.Entidades.Seguro.Aseguradora ConsultarAseguradoraPorId(int idAseguradora) {
            return base.Channel.ConsultarAseguradoraPorId(idAseguradora);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradoraPorIdAsync(int idAseguradora) {
            return base.Channel.ConsultarAseguradoraPorIdAsync(idAseguradora);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarAseguradora(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora) {
            return base.Channel.InsertarAseguradora(aseguradora);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarAseguradoraAsync(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora) {
            return base.Channel.InsertarAseguradoraAsync(aseguradora);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarAseguradora(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora) {
            return base.Channel.ActualizarAseguradora(aseguradora);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarAseguradoraAsync(BancaSeguros.Entidades.Seguro.Aseguradora aseguradora) {
            return base.Channel.ActualizarAseguradoraAsync(aseguradora);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Convenio> ConsultarConveniosPorIdAseguradora(int idAseguradora) {
            return base.Channel.ConsultarConveniosPorIdAseguradora(idAseguradora);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Convenio>> ConsultarConveniosPorIdAseguradoraAsync(int idAseguradora) {
            return base.Channel.ConsultarConveniosPorIdAseguradoraAsync(idAseguradora);
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarTipoDocumentoSeguro(int idSeguro, int idTipoIdentificacion) {
            return base.Channel.GuardarTipoDocumentoSeguro(idSeguro, idTipoIdentificacion);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarTipoDocumentoSeguroAsync(int idSeguro, int idTipoIdentificacion) {
            return base.Channel.GuardarTipoDocumentoSeguroAsync(idSeguro, idTipoIdentificacion);
        }
        
        public BancaSeguros.Entidades.General.Resultado EliminarTipoDocumentoSeguro(int idSeguro, int idTipoIdentificacion) {
            return base.Channel.EliminarTipoDocumentoSeguro(idSeguro, idTipoIdentificacion);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarTipoDocumentoSeguroAsync(int idSeguro, int idTipoIdentificacion) {
            return base.Channel.EliminarTipoDocumentoSeguroAsync(idSeguro, idTipoIdentificacion);
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarParametro(BancaSeguros.Entidades.Catalogo.Parametro parametro) {
            return base.Channel.GuardarParametro(parametro);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarParametroAsync(BancaSeguros.Entidades.Catalogo.Parametro parametro) {
            return base.Channel.GuardarParametroAsync(parametro);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizaParametroPorId(BancaSeguros.Entidades.Catalogo.Parametro parametro) {
            return base.Channel.ActualizaParametroPorId(parametro);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizaParametroPorIdAsync(BancaSeguros.Entidades.Catalogo.Parametro parametro) {
            return base.Channel.ActualizaParametroPorIdAsync(parametro);
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarSeguro(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro) {
            return base.Channel.GuardarSeguro(parametrizacionSeguro);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarSeguroAsync(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro) {
            return base.Channel.GuardarSeguroAsync(parametrizacionSeguro);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CanalVenta> ObtenerCanalesVentaActivos() {
            return base.Channel.ObtenerCanalesVentaActivos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CanalVenta>> ObtenerCanalesVentaActivosAsync() {
            return base.Channel.ObtenerCanalesVentaActivosAsync();
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Periodicidad> ObtenerPeriodicidadesActivas() {
            return base.Channel.ObtenerPeriodicidadesActivas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Periodicidad>> ObtenerPeriodicidadesActivasAsync() {
            return base.Channel.ObtenerPeriodicidadesActivasAsync();
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarTodosLosSeguros() {
            return base.Channel.ConsultarTodosLosSeguros();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarTodosLosSegurosAsync() {
            return base.Channel.ConsultarTodosLosSegurosAsync();
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarSeguroPorId(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro) {
            return base.Channel.ActualizarSeguroPorId(parametrizacionSeguro);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarSeguroPorIdAsync(BancaSeguros.Entidades.Administracion.ParametrizacionSeguro parametrizacionSeguro) {
            return base.Channel.ActualizarSeguroPorIdAsync(parametrizacionSeguro);
        }
        
        public BancaSeguros.Entidades.Administracion.ParametrizacionSeguro ConsultarInformacionSeguroPorId(int idSeguro) {
            return base.Channel.ConsultarInformacionSeguroPorId(idSeguro);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Administracion.ParametrizacionSeguro> ConsultarInformacionSeguroPorIdAsync(int idSeguro) {
            return base.Channel.ConsultarInformacionSeguroPorIdAsync(idSeguro);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarSegurosPorParametros(string nombreProducto, int codigoProducto, string nombreAseguradora) {
            return base.Channel.ConsultarSegurosPorParametros(nombreProducto, codigoProducto, nombreAseguradora);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarSegurosPorParametrosAsync(string nombreProducto, int codigoProducto, string nombreAseguradora) {
            return base.Channel.ConsultarSegurosPorParametrosAsync(nombreProducto, codigoProducto, nombreAseguradora);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarSegurosPorAseguradora(int idAseguradora) {
            return base.Channel.ConsultarSegurosPorAseguradora(idAseguradora);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarSegurosPorAseguradoraAsync(int idAseguradora) {
            return base.Channel.ConsultarSegurosPorAseguradoraAsync(idAseguradora);
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarIPC(BancaSeguros.Entidades.Catalogo.IPC ipc) {
            return base.Channel.GuardarIPC(ipc);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarIPCAsync(BancaSeguros.Entidades.Catalogo.IPC ipc) {
            return base.Channel.GuardarIPCAsync(ipc);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizaIPC(BancaSeguros.Entidades.Catalogo.IPC ipc) {
            return base.Channel.ActualizaIPC(ipc);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizaIPCAsync(BancaSeguros.Entidades.Catalogo.IPC ipc) {
            return base.Channel.ActualizaIPCAsync(ipc);
        }
        
        public BancaSeguros.Entidades.Catalogo.IPC ConsultarIPC() {
            return base.Channel.ConsultarIPC();
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Catalogo.IPC> ConsultarIPCAsync() {
            return base.Channel.ConsultarIPCAsync();
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.General.Auditoria> ObtenerAuditorias(BancaSeguros.Entidades.General.Auditoria auditoria) {
            return base.Channel.ObtenerAuditorias(auditoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.General.Auditoria>> ObtenerAuditoriasAsync(BancaSeguros.Entidades.General.Auditoria auditoria) {
            return base.Channel.ObtenerAuditoriasAsync(auditoria);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarNovedad(BancaSeguros.Entidades.Catalogo.Novedad novedad) {
            return base.Channel.InsertarNovedad(novedad);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarNovedadAsync(BancaSeguros.Entidades.Catalogo.Novedad novedad) {
            return base.Channel.InsertarNovedadAsync(novedad);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarNovedad(BancaSeguros.Entidades.Catalogo.Novedad novedad) {
            return base.Channel.ActualizarNovedad(novedad);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarNovedadAsync(BancaSeguros.Entidades.Catalogo.Novedad novedad) {
            return base.Channel.ActualizarNovedadAsync(novedad);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Novedad> ConsultarNovedades(BancaSeguros.Entidades.Catalogo.Novedad novedad) {
            return base.Channel.ConsultarNovedades(novedad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Novedad>> ConsultarNovedadesAsync(BancaSeguros.Entidades.Catalogo.Novedad novedad) {
            return base.Channel.ConsultarNovedadesAsync(novedad);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarCausalNovedad(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad) {
            return base.Channel.InsertarCausalNovedad(causalNovedad);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarCausalNovedadAsync(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad) {
            return base.Channel.InsertarCausalNovedadAsync(causalNovedad);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarCausalNovedad(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad) {
            return base.Channel.ActualizarCausalNovedad(causalNovedad);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarCausalNovedadAsync(BancaSeguros.Entidades.Catalogo.CausalNovedad causalNovedad) {
            return base.Channel.ActualizarCausalNovedadAsync(causalNovedad);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CausalNovedad> ConsultarCausalNovedad() {
            return base.Channel.ConsultarCausalNovedad();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.CausalNovedad>> ConsultarCausalNovedadAsync() {
            return base.Channel.ConsultarCausalNovedadAsync();
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarMensaje(BancaSeguros.Entidades.General.Mensaje mensaje) {
            return base.Channel.InsertarMensaje(mensaje);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarMensajeAsync(BancaSeguros.Entidades.General.Mensaje mensaje) {
            return base.Channel.InsertarMensajeAsync(mensaje);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarMensaje(BancaSeguros.Entidades.General.Mensaje mensaje) {
            return base.Channel.ActualizarMensaje(mensaje);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarMensajeAsync(BancaSeguros.Entidades.General.Mensaje mensaje) {
            return base.Channel.ActualizarMensajeAsync(mensaje);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.General.Mensaje> ConsultarMensajes(BancaSeguros.Entidades.General.Mensaje mensaje) {
            return base.Channel.ConsultarMensajes(mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.General.Mensaje>> ConsultarMensajesAsync(BancaSeguros.Entidades.General.Mensaje mensaje) {
            return base.Channel.ConsultarMensajesAsync(mensaje);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarAprobacionDual(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion) {
            return base.Channel.InsertarAprobacionDual(aprobacion);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarAprobacionDualAsync(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion) {
            return base.Channel.InsertarAprobacionDualAsync(aprobacion);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Administracion.AprobacionDual> ConsultarAprobacionesControlDual(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion) {
            return base.Channel.ConsultarAprobacionesControlDual(aprobacion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Administracion.AprobacionDual>> ConsultarAprobacionesControlDualAsync(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion) {
            return base.Channel.ConsultarAprobacionesControlDualAsync(aprobacion);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarAprobacionDual(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion) {
            return base.Channel.ActualizarAprobacionDual(aprobacion);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarAprobacionDualAsync(BancaSeguros.Entidades.Administracion.AprobacionDual aprobacion) {
            return base.Channel.ActualizarAprobacionDualAsync(aprobacion);
        }
        
        public BancaSeguros.Entidades.Administracion.AprobacionDual ConsultarAprobacionesControlDualPorId(int idAprobacionDual) {
            return base.Channel.ConsultarAprobacionesControlDualPorId(idAprobacionDual);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Administracion.AprobacionDual> ConsultarAprobacionesControlDualPorIdAsync(int idAprobacionDual) {
            return base.Channel.ConsultarAprobacionesControlDualPorIdAsync(idAprobacionDual);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarVariableProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.InsertarVariableProducto(variable);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarVariableProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.InsertarVariableProductoAsync(variable);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarVariableProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.ActualizarVariableProducto(variable);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarVariableProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.ActualizarVariableProductoAsync(variable);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto> ConsultarVariablesProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.ConsultarVariablesProducto(variable);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto>> ConsultarVariablesProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.ConsultarVariablesProductoAsync(variable);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto> ConsultarVariablesProductoActivas(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.ConsultarVariablesProductoActivas(variable);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.VariableProducto>> ConsultarVariablesProductoActivasAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.ConsultarVariablesProductoActivasAsync(variable);
        }
        
        public BancaSeguros.Entidades.General.Resultado EliminarVariableProducto(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.EliminarVariableProducto(variable);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarVariableProductoAsync(BancaSeguros.Entidades.Seguro.VariableProducto variable) {
            return base.Channel.EliminarVariableProductoAsync(variable);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarMaestra(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.InsertarMaestra(maestra);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarMaestraAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.InsertarMaestraAsync(maestra);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarMaestra(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.ActualizarMaestra(maestra);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarMaestraAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.ActualizarMaestraAsync(maestra);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Maestra> ConsultarMaestras(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.ConsultarMaestras(maestra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Maestra>> ConsultarMaestrasAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.ConsultarMaestrasAsync(maestra);
        }
        
        public BancaSeguros.Entidades.General.Resultado EliminarMaestra(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.EliminarMaestra(maestra);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarMaestraAsync(BancaSeguros.Entidades.Catalogo.Maestra maestra) {
            return base.Channel.EliminarMaestraAsync(maestra);
        }
        
        public BancaSeguros.Entidades.General.Resultado InsertarItemMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.InsertarItemMaestra(itemMaestra);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> InsertarItemMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.InsertarItemMaestraAsync(itemMaestra);
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarItemMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.ActualizarItemMaestra(itemMaestra);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarItemMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.ActualizarItemMaestraAsync(itemMaestra);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.ItemMaestra> ConsultarItemsMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.ConsultarItemsMaestra(itemMaestra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.ItemMaestra>> ConsultarItemsMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.ConsultarItemsMaestraAsync(itemMaestra);
        }
        
        public BancaSeguros.Entidades.General.Resultado EliminarItemMaestra(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.EliminarItemMaestra(itemMaestra);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarItemMaestraAsync(BancaSeguros.Entidades.Catalogo.ItemMaestra itemMaestra) {
            return base.Channel.EliminarItemMaestraAsync(itemMaestra);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradorasActivas() {
            return base.Channel.ConsultarAseguradorasActivas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora>> ConsultarAseguradorasActivasAsync() {
            return base.Channel.ConsultarAseguradorasActivasAsync();
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposPoliza> ConsultarPolizas(int opcion) {
            return base.Channel.ConsultarPolizas(opcion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposPoliza>> ConsultarPolizasAsync(int opcion) {
            return base.Channel.ConsultarPolizasAsync(opcion);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCobros> ConsultarCobros(int opcion) {
            return base.Channel.ConsultarCobros(opcion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCobros>> ConsultarCobrosAsync(int opcion) {
            return base.Channel.ConsultarCobrosAsync(opcion);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones> ConsultarCancelaciones(int opcion) {
            return base.Channel.ConsultarCancelaciones(opcion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones>> ConsultarCancelacionesAsync(int opcion) {
            return base.Channel.ConsultarCancelacionesAsync(opcion);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones> ConsultarFiltrosCancelaciones() {
            return base.Channel.ConsultarFiltrosCancelaciones();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.CamposCancelaciones>> ConsultarFiltrosCancelacionesAsync() {
            return base.Channel.ConsultarFiltrosCancelacionesAsync();
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarDatosArchivoPlano(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo) {
            return base.Channel.GuardarDatosArchivoPlano(datosArchivo);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarDatosArchivoPlanoAsync(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo) {
            return base.Channel.GuardarDatosArchivoPlanoAsync(datosArchivo);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Planos.ArchivoPlano> ConsultarDatosGrilla() {
            return base.Channel.ConsultarDatosGrilla();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Planos.ArchivoPlano>> ConsultarDatosGrillaAsync() {
            return base.Channel.ConsultarDatosGrillaAsync();
        }
        
        public BancaSeguros.Entidades.General.Resultado ActualizarDatosArchivoPlano(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo) {
            return base.Channel.ActualizarDatosArchivoPlano(datosArchivo);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ActualizarDatosArchivoPlanoAsync(BancaSeguros.Entidades.Planos.ArchivoPlano datosArchivo) {
            return base.Channel.ActualizarDatosArchivoPlanoAsync(datosArchivo);
        }
        
        public BancaSeguros.Entidades.General.Resultado EliminarDatosArchivoPlano(int idProgramacion, string usuario) {
            return base.Channel.EliminarDatosArchivoPlano(idProgramacion, usuario);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> EliminarDatosArchivoPlanoAsync(int idProgramacion, string usuario) {
            return base.Channel.EliminarDatosArchivoPlanoAsync(idProgramacion, usuario);
        }
    }
}
