CREATE TABLE [dbo].[MIG_VentaCarga] (
    [id]        INT           IDENTITY (1, 1) NOT NULL,
    [columna1]  VARCHAR (50)  NULL,
    [columna2]  VARCHAR (10)  NULL,
    [columna3]  VARCHAR (10)  NULL,
    [columna4]  VARCHAR (16)  NULL,
    [columna5]  VARCHAR (50)  NULL,
    [columna6]  VARCHAR (50)  NULL,
    [columna7]  VARCHAR (50)  NULL,
    [columna8]  VARCHAR (50)  NULL,
    [columna9]  VARCHAR (2)   NULL,
    [columna10] VARCHAR (8)   NULL,
    [columna11] VARCHAR (50)  NULL,
    [columna12] VARCHAR (50)  NULL,
    [columna13] VARCHAR (50)  NULL,
    [columna14] VARCHAR (200) NULL,
    [columna15] VARCHAR (50)  NULL,
    [columna16] VARCHAR (100) NULL,
    [columna17] VARCHAR (50)  NULL,
    [columna18] VARCHAR (50)  NULL,
    [columna19] VARCHAR (50)  NULL,
    [columna20] VARCHAR (50)  NULL,
    [columna21] VARCHAR (50)  NULL,
    [columna22] VARCHAR (50)  NULL,
    [columna23] VARCHAR (50)  NULL,
    [columna24] VARCHAR (50)  NULL,
    [columna25] VARCHAR (50)  NULL,
    [columna26] VARCHAR (16)  NULL,
    [columna27] VARCHAR (50)  NULL,
    [columna28] VARCHAR (10)  NULL
);

