CREATE TABLE [dbo].[SEG_LogArchivoCobro] (
    [tipoNovedad]     VARCHAR (1)     NULL,
    [tipoTransaccion] INT             NULL,
    [fecha]           VARCHAR (8)     NOT NULL,
    [usuario]         VARCHAR (4)     NULL,
    [ctaBancoOrigen]  VARCHAR (50)    NULL,
    [productoOrigen]  INT             NULL,
    [ctaBancoDestino] VARCHAR (1)     NULL,
    [productoDestino] VARCHAR (1)     NULL,
    [oficina]         INT             NULL,
    [fechaHora]       NVARCHAR (4000) NOT NULL,
    [nroControl]      VARCHAR (1)     NULL,
    [correccion]      VARCHAR (1)     NULL,
    [moneda]          INT             NULL,
    [cheque]          INT             NULL,
    [desprendible]    VARCHAR (1)     NULL,
    [tipoCheque]      VARCHAR (1)     NULL,
    [banco]           VARCHAR (1)     NULL,
    [cuentaGirada]    VARCHAR (1)     NULL,
    [endoso]          VARCHAR (1)     NULL,
    [montoEfectivo]   VARCHAR (44)    NULL,
    [montoLocal]      VARCHAR (18)    NULL,
    [montoPropio]     VARCHAR (18)    NULL,
    [montoRemCobro]   VARCHAR (18)    NULL,
    [montoRemNeg]     VARCHAR (18)    NULL,
    [montoIVA]        VARCHAR (18)    NULL,
    [montoComision]   VARCHAR (18)    NULL,
    [referencia1]     VARCHAR (50)    NULL,
    [referencia2]     INT             NULL,
    [referencia3]     INT             NULL,
    [referencia4]     INT             NULL,
    [referencia5]     INT             NULL,
    [convenio]        INT             NULL,
    [causa]           VARCHAR (3)     NULL,
    [causal]          VARCHAR (1)     NULL,
    [depto]           VARCHAR (1)     NULL,
    [comentario]      VARCHAR (1)     NULL,
    [tarjetaCred]     VARCHAR (1)     NULL,
    [establecimiento] VARCHAR (10)    NULL,
    [tsFechaEfectiva] VARCHAR (1)     NULL,
    [identificacion]  VARCHAR (1)     NULL,
    [claseImpuesto]   VARCHAR (1)     NULL,
    [tipoVarios]      VARCHAR (1)     NULL,
    [tipoPersona]     VARCHAR (1)     NULL,
    [sticker]         VARCHAR (1)     NULL,
    [administracion]  VARCHAR (1)     NULL,
    [formaPago]       VARCHAR (3)     NULL,
    [institucion]     VARCHAR (1)     NULL,
    [cajaOrigen]      VARCHAR (1)     NULL,
    [cajaDestino]     VARCHAR (1)     NULL,
    [usuarioOrigen]   VARCHAR (1)     NULL,
    [secuencial]      INT             NOT NULL,
    [numControlRech]  VARCHAR (1)     NULL,
    [codError]        VARCHAR (1)     NULL,
    [descError]       VARCHAR (1)     NULL,
    [posicion]        VARCHAR (1)     NULL,
    [periodoCobro]    VARCHAR (10)    NULL,
    [nombreArchivo]   VARCHAR (50)    NULL,
    [fechaProceso]    DATETIME        NULL
);

