CREATE TABLE [dbo].[SEG_Venta] (
    [idVenta]                   INT             IDENTITY (1, 1) NOT NULL,
    [idAsesor]                  VARCHAR (50)    NOT NULL,
    [idOficina]                 INT             NOT NULL,
    [consecutivo]               VARCHAR (50)    NOT NULL,
    [fechaCreacion]             DATETIME        NOT NULL,
    [idTipoIdentificacion]      INT             NOT NULL,
    [identificacion]            VARCHAR (16)    NOT NULL,
    [primerNombre]              VARCHAR (50)    NULL,
    [segundoNombre]             VARCHAR (50)    NULL,
    [primerApellido]            VARCHAR (50)    NULL,
    [segundoApellido]           VARCHAR (50)    NULL,
    [fechaNacimiento]           DATETIME        NULL,
    [ciudadNacimiento]          VARCHAR (50)    NULL,
    [nacionalidad]              VARCHAR (50)    NULL,
    [IdGenero]                  INT             NULL,
    [direccion]                 VARCHAR (200)   NULL,
    [ciudadResidencia]          VARCHAR (50)    NULL,
    [telefono]                  VARCHAR (50)    NULL,
    [celular]                   VARCHAR (50)    NULL,
    [correo]                    VARCHAR (100)   NULL,
    [razonSocial]               VARCHAR (50)    NULL,
    [fechaCreacionEmpresa]      DATETIME        NULL,
    [representanteLegal]        VARCHAR (200)   NULL,
    [actividadEconomicaCliente] VARCHAR (150)   NULL,
    [codigoEstadoPoliza]        INT             NULL,
    [valorPoliza]               DECIMAL (18, 2) NOT NULL,
    [codigoTipoCuenta]          INT             NULL,
    [numeroCuenta]              VARCHAR (50)    NULL,
    [ultimoIPC]                 INT             NULL,
    [identificacionAseguradora] VARCHAR (50)    NOT NULL,
    [nombreAseguradora]         VARCHAR (50)    NOT NULL,
    [codigoSeguro]              INT             NOT NULL,
    [nombreSeguro]              VARCHAR (50)    NOT NULL,
    [codigoPlan]                INT             NOT NULL,
    [nombrePlan]                VARCHAR (50)    NULL,
    [codigoConvenio]            INT             NOT NULL,
    [nombrePeriodicidad]        VARCHAR (50)    NULL,
    [numMesesPeriodicidad]      INT             NOT NULL,
    [codigoCanalVenta]          INT             NOT NULL,
    [nombreCanalVenta]          VARCHAR (50)    NOT NULL,
    [nombreOficina]             VARCHAR (50)    NOT NULL,
    [nombreCiudadOficina]       VARCHAR (50)    NOT NULL,
    [nombreAsesor]              VARCHAR (100)   NOT NULL,
    [identificacionAsesor]      VARCHAR (20)    NOT NULL,
    [nombreIdentificacion]      VARCHAR (50)    NOT NULL,
    [nombreGenero]              VARCHAR (20)    NOT NULL,
    [nombreTipoCuenta]          VARCHAR (50)    NOT NULL,
    [departamentoResidencia]    VARCHAR (50)    NOT NULL,
    [altura]                    INT             NOT NULL,
    [codigoDANE]                VARCHAR (50)    NULL,
    CONSTRAINT [PK_SEG_Venta] PRIMARY KEY CLUSTERED ([idVenta] ASC),
    CONSTRAINT [FK_SEG_Venta_SEG_Asesor] FOREIGN KEY ([idAsesor]) REFERENCES [dbo].[SEG_Asesor] ([idAsesor]),
    CONSTRAINT [FK_SEG_Venta_SEG_Genero] FOREIGN KEY ([IdGenero]) REFERENCES [dbo].[SEG_Genero] ([idGenero]),
    CONSTRAINT [FK_SEG_Venta_SEG_Productos] FOREIGN KEY ([codigoTipoCuenta]) REFERENCES [dbo].[SEG_Productos] ([codigo])
);



