//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Infraestructura.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Parametros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Infraestructura.Configuraciones.Parametros", typeof(Parametros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alias.
        /// </summary>
        internal static string alias {
            get {
                return ResourceManager.GetString("alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional.
        /// </summary>
        internal static string Conditional {
            get {
                return ResourceManager.GetString("Conditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFileName.
        /// </summary>
        internal static string DataFileName {
            get {
                return ResourceManager.GetString("DataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentGenerationInfo.
        /// </summary>
        internal static string DocumentGenerationInfo {
            get {
                return ResourceManager.GetString("DocumentGenerationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string p {
            get {
                return ResourceManager.GetString("p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        internal static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdt.
        /// </summary>
        internal static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdtContent.
        /// </summary>
        internal static string sdtContent {
            get {
                return ResourceManager.GetString("sdtContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdtPr.
        /// </summary>
        internal static string sdtPr {
            get {
                return ResourceManager.GetString("sdtPr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectDocumentName.
        /// </summary>
        internal static string SelectDocumentName {
            get {
                return ResourceManager.GetString("SelectDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectDocuments.
        /// </summary>
        internal static string SelectDocuments {
            get {
                return ResourceManager.GetString("SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectRepeatingData.
        /// </summary>
        internal static string SelectRepeatingData {
            get {
                return ResourceManager.GetString("SelectRepeatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectRows.
        /// </summary>
        internal static string SelectRows {
            get {
                return ResourceManager.GetString("SelectRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectTestValue.
        /// </summary>
        internal static string SelectTestValue {
            get {
                return ResourceManager.GetString("SelectTestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectValue.
        /// </summary>
        internal static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringFormat.
        /// </summary>
        internal static string StringFormat {
            get {
                return ResourceManager.GetString("StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl.
        /// </summary>
        internal static string tbl {
            get {
                return ResourceManager.GetString("tbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tc.
        /// </summary>
        internal static string tc {
            get {
                return ResourceManager.GetString("tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to val.
        /// </summary>
        internal static string val {
            get {
                return ResourceManager.GetString("val", resourceCulture);
            }
        }
    }
}
