//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LlavesUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LlavesUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LlavesUI", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPW004.
        /// </summary>
        internal static string CatchCargarPlantilla {
            get {
                return ResourceManager.GetString("CatchCargarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPW001.
        /// </summary>
        internal static string CatchConstruirPDF {
            get {
                return ResourceManager.GetString("CatchConstruirPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPW002.
        /// </summary>
        internal static string CatchConstruirPlantilla {
            get {
                return ResourceManager.GetString("CatchConstruirPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIW001.
        /// </summary>
        internal static string CatchReimpresion {
            get {
                return ResourceManager.GetString("CatchReimpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIW002.
        /// </summary>
        internal static string ConsultarVentaVacia {
            get {
                return ResourceManager.GetString("ConsultarVentaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string EventoPlantilla {
            get {
                return ResourceManager.GetString("EventoPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string EventoReimpresion {
            get {
                return ResourceManager.GetString("EventoReimpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPW003.
        /// </summary>
        internal static string PlantillaAlmacenada {
            get {
                return ResourceManager.GetString("PlantillaAlmacenada", resourceCulture);
            }
        }
    }
}
