//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Parametros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Parametros", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimerNombreCliente,SegundoNombreCliente,PrimerApellidoCliente,SegundoApellidoCliente,NumeroIdentificacionCliente,TipoIdentificacionAbreviadoCliente,TipoIdentificacionDescripcionCliente,FechaNacimientoCliente,CiudadNacimientoCliente,GeneroCliente,ActividadEconomicaCliente,DireccionCliente,TelefonoCliente,CiudadResidenciaCliente,DepartamenoCliente,NacionalidadCliente,CelularCliente,TipoCuentaCliente,NumeroCuentaCliente,FechaVencimientoTarjetaCliente.
        /// </summary>
        internal static string CamposCliente {
            get {
                return ResourceManager.GetString("CamposCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string FormatoDDMMYYYY {
            get {
                return ResourceManager.GetString("FormatoDDMMYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinimaVigenciaToken.
        /// </summary>
        internal static string MinimaVigenciaToken {
            get {
                return ResourceManager.GetString("MinimaVigenciaToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .docx.
        /// </summary>
        internal static string PuntoDocx {
            get {
                return ResourceManager.GetString("PuntoDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        internal static string PuntoPDF {
            get {
                return ResourceManager.GetString("PuntoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        internal static string PuntoPNG {
            get {
                return ResourceManager.GetString("PuntoPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Plantillas/.
        /// </summary>
        internal static string RutaArchivosPlantilla {
            get {
                return ResourceManager.GetString("RutaArchivosPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../DocumentosPolizas/.
        /// </summary>
        internal static string RutaArchivosPoliza {
            get {
                return ResourceManager.GetString("RutaArchivosPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Recurso/XML_Ejemplo.xml.
        /// </summary>
        internal static string RutaArchivoXmlDummie {
            get {
                return ResourceManager.GetString("RutaArchivoXmlDummie", resourceCulture);
            }
        }
    }
}
