//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSegurosUI.ServicioVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioVenta.IServicioVenta")]
    public interface IServicioVenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarInformacionCliente", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarInformacionClienteResponse")]
        BancaSeguros.Entidades.Venta.Cliente ConsultarInformacionCliente(BancaSeguros.Entidades.Venta.Cliente usuario, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarInformacionCliente", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarInformacionClienteResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.Cliente> ConsultarInformacionClienteAsync(BancaSeguros.Entidades.Venta.Cliente usuario, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ClienteEstaEnListasInhibitorias", ReplyAction="http://tempuri.org/IServicioVenta/ClienteEstaEnListasInhibitoriasResponse")]
        BancaSeguros.Entidades.Venta.Cliente ClienteEstaEnListasInhibitorias(BancaSeguros.Entidades.Venta.Cliente usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ClienteEstaEnListasInhibitorias", ReplyAction="http://tempuri.org/IServicioVenta/ClienteEstaEnListasInhibitoriasResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.Cliente> ClienteEstaEnListasInhibitoriasAsync(BancaSeguros.Entidades.Venta.Cliente usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarProductosBancarios", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarProductosBancariosResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoBancario> ConsultarProductosBancarios(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarProductosBancarios", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarProductosBancariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoBancario>> ConsultarProductosBancariosAsync(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/CreacionRapidaCliente", ReplyAction="http://tempuri.org/IServicioVenta/CreacionRapidaClienteResponse")]
        BancaSeguros.Entidades.General.Resultado CreacionRapidaCliente(BancaSeguros.Entidades.Venta.Cliente cliente, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/CreacionRapidaCliente", ReplyAction="http://tempuri.org/IServicioVenta/CreacionRapidaClienteResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> CreacionRapidaClienteAsync(BancaSeguros.Entidades.Venta.Cliente cliente, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/GenerarDebitoACuentaCliente", ReplyAction="http://tempuri.org/IServicioVenta/GenerarDebitoACuentaClienteResponse")]
        BancaSeguros.Entidades.General.Resultado GenerarDebitoACuentaCliente(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/GenerarDebitoACuentaCliente", ReplyAction="http://tempuri.org/IServicioVenta/GenerarDebitoACuentaClienteResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GenerarDebitoACuentaClienteAsync(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/GenerarCreditoACuentaAseguradora", ReplyAction="http://tempuri.org/IServicioVenta/GenerarCreditoACuentaAseguradoraResponse")]
        BancaSeguros.Entidades.General.Resultado GenerarCreditoACuentaAseguradora(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/GenerarCreditoACuentaAseguradora", ReplyAction="http://tempuri.org/IServicioVenta/GenerarCreditoACuentaAseguradoraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GenerarCreditoACuentaAseguradoraAsync(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarInformacionClienteActual", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarInformacionClienteActualResponse")]
        BancaSeguros.Entidades.Venta.Cliente ConsultarInformacionClienteActual(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarInformacionClienteActual", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarInformacionClienteActualResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.Cliente> ConsultarInformacionClienteActualAsync(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarLosSegurosAVender", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarLosSegurosAVenderResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarLosSegurosAVender(int idTipoDeIdentificacion, System.DateTime fechaDeNacimientoCliente, int genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarLosSegurosAVender", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarLosSegurosAVenderResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarLosSegurosAVenderAsync(int idTipoDeIdentificacion, System.DateTime fechaDeNacimientoCliente, int genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarSegurosPorCodigoYAseguradora", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarSegurosPorCodigoYAseguradoraResponse")]
        BancaSeguros.Entidades.General.Resultado ConsultarSegurosPorCodigoYAseguradora(int codigoSeguro, int codigoAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarSegurosPorCodigoYAseguradora", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarSegurosPorCodigoYAseguradoraResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ConsultarSegurosPorCodigoYAseguradoraAsync(int codigoSeguro, int codigoAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarPlanesPorIdSeguro", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarPlanesPorIdSeguroResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Plan> ConsultarPlanesPorIdSeguro(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarPlanesPorIdSeguro", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarPlanesPorIdSeguroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Plan>> ConsultarPlanesPorIdSeguroAsync(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/GenerarProcesoFinalDeLaVenta", ReplyAction="http://tempuri.org/IServicioVenta/GenerarProcesoFinalDeLaVentaResponse")]
        BancaSeguros.Entidades.Venta.ResultadoVentaPoliza GenerarProcesoFinalDeLaVenta(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/GenerarProcesoFinalDeLaVenta", ReplyAction="http://tempuri.org/IServicioVenta/GenerarProcesoFinalDeLaVentaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoVentaPoliza> GenerarProcesoFinalDeLaVentaAsync(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerDocumentoVentaPoliza", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerDocumentoVentaPolizaResponse")]
        BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza ObtenerDocumentoVentaPoliza(string consecutivoPoliza, int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerDocumentoVentaPoliza", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerDocumentoVentaPolizaResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza> ObtenerDocumentoVentaPolizaAsync(string consecutivoPoliza, int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarAseguradorasActivas", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarAseguradorasActivasResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradorasActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarAseguradorasActivas", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarAseguradorasActivasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora>> ConsultarAseguradorasActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerCategoriasPorIdSubProducto", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerCategoriasPorIdSubProductoResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Categoria> ObtenerCategoriasPorIdSubProducto(int idSubProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerCategoriasPorIdSubProducto", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerCategoriasPorIdSubProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Categoria>> ObtenerCategoriasPorIdSubProductoAsync(int idSubProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarProductosNoPermitidosPorSeguro", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarProductosNoPermitidosPorSeguroResponse" +
            "")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoNoPermitido> ConsultarProductosNoPermitidosPorSeguro(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarProductosNoPermitidosPorSeguro", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarProductosNoPermitidosPorSeguroResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoNoPermitido>> ConsultarProductosNoPermitidosPorSeguroAsync(int idSeguro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerSubProductosPorCodigoProducto", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerSubProductosPorCodigoProductoResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.SubProducto> ObtenerSubProductosPorCodigoProducto(int codigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerSubProductosPorCodigoProducto", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerSubProductosPorCodigoProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.SubProducto>> ObtenerSubProductosPorCodigoProductoAsync(int codigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerProductosBancariosActivos", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerProductosBancariosActivosResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Producto> ObtenerProductosBancariosActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ObtenerProductosBancariosActivos", ReplyAction="http://tempuri.org/IServicioVenta/ObtenerProductosBancariosActivosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Producto>> ObtenerProductosBancariosActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarVentaPorCliente", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarVentaPorClienteResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta> ConsultarVentaPorCliente(BancaSeguros.Entidades.Venta.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarVentaPorCliente", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarVentaPorClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta>> ConsultarVentaPorClienteAsync(BancaSeguros.Entidades.Venta.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarVentaPorClienteDiaHabil", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarVentaPorClienteDiaHabilResponse")]
        System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta> ConsultarVentaPorClienteDiaHabil(BancaSeguros.Entidades.Venta.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarVentaPorClienteDiaHabil", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarVentaPorClienteDiaHabilResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta>> ConsultarVentaPorClienteDiaHabilAsync(BancaSeguros.Entidades.Venta.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarPolizaReimpresion", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarPolizaReimpresionResponse")]
        BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza ConsultarPolizaReimpresion(string consecutivoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarPolizaReimpresion", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarPolizaReimpresionResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza> ConsultarPolizaReimpresionAsync(string consecutivoPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarVentasCuentasPorCliente", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarVentasCuentasPorClienteResponse")]
        BancaSeguros.Entidades.General.Resultado ConsultarVentasCuentasPorCliente(BancaSeguros.Entidades.Venta.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVenta/ConsultarVentasCuentasPorCliente", ReplyAction="http://tempuri.org/IServicioVenta/ConsultarVentasCuentasPorClienteResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ConsultarVentasCuentasPorClienteAsync(BancaSeguros.Entidades.Venta.Cliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioVentaChannel : BancaSegurosUI.ServicioVenta.IServicioVenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioVentaClient : System.ServiceModel.ClientBase<BancaSegurosUI.ServicioVenta.IServicioVenta>, BancaSegurosUI.ServicioVenta.IServicioVenta {
        
        public ServicioVentaClient() {
        }
        
        public ServicioVentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioVentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancaSeguros.Entidades.Venta.Cliente ConsultarInformacionCliente(BancaSeguros.Entidades.Venta.Cliente usuario, string userName) {
            return base.Channel.ConsultarInformacionCliente(usuario, userName);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.Cliente> ConsultarInformacionClienteAsync(BancaSeguros.Entidades.Venta.Cliente usuario, string userName) {
            return base.Channel.ConsultarInformacionClienteAsync(usuario, userName);
        }
        
        public BancaSeguros.Entidades.Venta.Cliente ClienteEstaEnListasInhibitorias(BancaSeguros.Entidades.Venta.Cliente usuario) {
            return base.Channel.ClienteEstaEnListasInhibitorias(usuario);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.Cliente> ClienteEstaEnListasInhibitoriasAsync(BancaSeguros.Entidades.Venta.Cliente usuario) {
            return base.Channel.ClienteEstaEnListasInhibitoriasAsync(usuario);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoBancario> ConsultarProductosBancarios(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario) {
            return base.Channel.ConsultarProductosBancarios(cliente, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoBancario>> ConsultarProductosBancariosAsync(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario) {
            return base.Channel.ConsultarProductosBancariosAsync(cliente, usuario);
        }
        
        public BancaSeguros.Entidades.General.Resultado CreacionRapidaCliente(BancaSeguros.Entidades.Venta.Cliente cliente, string userName) {
            return base.Channel.CreacionRapidaCliente(cliente, userName);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> CreacionRapidaClienteAsync(BancaSeguros.Entidades.Venta.Cliente cliente, string userName) {
            return base.Channel.CreacionRapidaClienteAsync(cliente, userName);
        }
        
        public BancaSeguros.Entidades.General.Resultado GenerarDebitoACuentaCliente(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta) {
            return base.Channel.GenerarDebitoACuentaCliente(registrarVenta);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GenerarDebitoACuentaClienteAsync(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta) {
            return base.Channel.GenerarDebitoACuentaClienteAsync(registrarVenta);
        }
        
        public BancaSeguros.Entidades.General.Resultado GenerarCreditoACuentaAseguradora(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta) {
            return base.Channel.GenerarCreditoACuentaAseguradora(registrarVenta);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GenerarCreditoACuentaAseguradoraAsync(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta) {
            return base.Channel.GenerarCreditoACuentaAseguradoraAsync(registrarVenta);
        }
        
        public BancaSeguros.Entidades.Venta.Cliente ConsultarInformacionClienteActual(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario, string token) {
            return base.Channel.ConsultarInformacionClienteActual(cliente, usuario, token);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.Cliente> ConsultarInformacionClienteActualAsync(BancaSeguros.Entidades.Venta.Cliente cliente, string usuario, string token) {
            return base.Channel.ConsultarInformacionClienteActualAsync(cliente, usuario, token);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro> ConsultarLosSegurosAVender(int idTipoDeIdentificacion, System.DateTime fechaDeNacimientoCliente, int genero) {
            return base.Channel.ConsultarLosSegurosAVender(idTipoDeIdentificacion, fechaDeNacimientoCliente, genero);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Seguro>> ConsultarLosSegurosAVenderAsync(int idTipoDeIdentificacion, System.DateTime fechaDeNacimientoCliente, int genero) {
            return base.Channel.ConsultarLosSegurosAVenderAsync(idTipoDeIdentificacion, fechaDeNacimientoCliente, genero);
        }
        
        public BancaSeguros.Entidades.General.Resultado ConsultarSegurosPorCodigoYAseguradora(int codigoSeguro, int codigoAseguradora) {
            return base.Channel.ConsultarSegurosPorCodigoYAseguradora(codigoSeguro, codigoAseguradora);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ConsultarSegurosPorCodigoYAseguradoraAsync(int codigoSeguro, int codigoAseguradora) {
            return base.Channel.ConsultarSegurosPorCodigoYAseguradoraAsync(codigoSeguro, codigoAseguradora);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Plan> ConsultarPlanesPorIdSeguro(int idSeguro) {
            return base.Channel.ConsultarPlanesPorIdSeguro(idSeguro);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Plan>> ConsultarPlanesPorIdSeguroAsync(int idSeguro) {
            return base.Channel.ConsultarPlanesPorIdSeguroAsync(idSeguro);
        }
        
        public BancaSeguros.Entidades.Venta.ResultadoVentaPoliza GenerarProcesoFinalDeLaVenta(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta) {
            return base.Channel.GenerarProcesoFinalDeLaVenta(registrarVenta);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoVentaPoliza> GenerarProcesoFinalDeLaVentaAsync(BancaSeguros.Entidades.Venta.RegistrarVenta registrarVenta) {
            return base.Channel.GenerarProcesoFinalDeLaVentaAsync(registrarVenta);
        }
        
        public BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza ObtenerDocumentoVentaPoliza(string consecutivoPoliza, int idSeguro) {
            return base.Channel.ObtenerDocumentoVentaPoliza(consecutivoPoliza, idSeguro);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza> ObtenerDocumentoVentaPolizaAsync(string consecutivoPoliza, int idSeguro) {
            return base.Channel.ObtenerDocumentoVentaPolizaAsync(consecutivoPoliza, idSeguro);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora> ConsultarAseguradorasActivas() {
            return base.Channel.ConsultarAseguradorasActivas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Seguro.Aseguradora>> ConsultarAseguradorasActivasAsync() {
            return base.Channel.ConsultarAseguradorasActivasAsync();
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Categoria> ObtenerCategoriasPorIdSubProducto(int idSubProducto) {
            return base.Channel.ObtenerCategoriasPorIdSubProducto(idSubProducto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Categoria>> ObtenerCategoriasPorIdSubProductoAsync(int idSubProducto) {
            return base.Channel.ObtenerCategoriasPorIdSubProductoAsync(idSubProducto);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoNoPermitido> ConsultarProductosNoPermitidosPorSeguro(int idSeguro) {
            return base.Channel.ConsultarProductosNoPermitidosPorSeguro(idSeguro);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ProductoNoPermitido>> ConsultarProductosNoPermitidosPorSeguroAsync(int idSeguro) {
            return base.Channel.ConsultarProductosNoPermitidosPorSeguroAsync(idSeguro);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.SubProducto> ObtenerSubProductosPorCodigoProducto(int codigoProducto) {
            return base.Channel.ObtenerSubProductosPorCodigoProducto(codigoProducto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.SubProducto>> ObtenerSubProductosPorCodigoProductoAsync(int codigoProducto) {
            return base.Channel.ObtenerSubProductosPorCodigoProductoAsync(codigoProducto);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Producto> ObtenerProductosBancariosActivos() {
            return base.Channel.ObtenerProductosBancariosActivos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Catalogo.Producto>> ObtenerProductosBancariosActivosAsync() {
            return base.Channel.ObtenerProductosBancariosActivosAsync();
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta> ConsultarVentaPorCliente(BancaSeguros.Entidades.Venta.Cliente cliente) {
            return base.Channel.ConsultarVentaPorCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta>> ConsultarVentaPorClienteAsync(BancaSeguros.Entidades.Venta.Cliente cliente) {
            return base.Channel.ConsultarVentaPorClienteAsync(cliente);
        }
        
        public System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta> ConsultarVentaPorClienteDiaHabil(BancaSeguros.Entidades.Venta.Cliente cliente) {
            return base.Channel.ConsultarVentaPorClienteDiaHabil(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BancaSeguros.Entidades.Venta.ConsultarVenta>> ConsultarVentaPorClienteDiaHabilAsync(BancaSeguros.Entidades.Venta.Cliente cliente) {
            return base.Channel.ConsultarVentaPorClienteDiaHabilAsync(cliente);
        }
        
        public BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza ConsultarPolizaReimpresion(string consecutivoPoliza) {
            return base.Channel.ConsultarPolizaReimpresion(consecutivoPoliza);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Venta.ResultadoDocumentoPoliza> ConsultarPolizaReimpresionAsync(string consecutivoPoliza) {
            return base.Channel.ConsultarPolizaReimpresionAsync(consecutivoPoliza);
        }
        
        public BancaSeguros.Entidades.General.Resultado ConsultarVentasCuentasPorCliente(BancaSeguros.Entidades.Venta.Cliente cliente) {
            return base.Channel.ConsultarVentasCuentasPorCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ConsultarVentasCuentasPorClienteAsync(BancaSeguros.Entidades.Venta.Cliente cliente) {
            return base.Channel.ConsultarVentasCuentasPorClienteAsync(cliente);
        }
    }
}
