//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Sincronizacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Sincronizacion.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Servicio.
        /// </summary>
        internal static string EstadoServicio {
            get {
                return ResourceManager.GetString("EstadoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiempoEjecucion: {0} minutos.
        /// </summary>
        internal static string MensajeTiempoEjecucion {
            get {
                return ResourceManager.GetString("MensajeTiempoEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Ejecutando Proceso.
        /// </summary>
        internal static string OperacionError {
            get {
                return ResourceManager.GetString("OperacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Ejecutando Proceso al iniciar el servicio.
        /// </summary>
        internal static string OperacionErrorIniciado {
            get {
                return ResourceManager.GetString("OperacionErrorIniciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error realizando la validacion de incio.
        /// </summary>
        internal static string OperacionErrorValidando {
            get {
                return ResourceManager.GetString("OperacionErrorValidando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación fue realizada con exito..
        /// </summary>
        internal static string OperacionRealizada {
            get {
                return ResourceManager.GetString("OperacionRealizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiempoEjecucion.
        /// </summary>
        internal static string ParametroTiempoEjecucion {
            get {
                return ResourceManager.GetString("ParametroTiempoEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiempoIntervaloHora.
        /// </summary>
        internal static string ParametroTiempoIntervaloHora {
            get {
                return ResourceManager.GetString("ParametroTiempoIntervaloHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiempoIntervaloMinutos.
        /// </summary>
        internal static string ParametroTiempoIntervaloMinutos {
            get {
                return ResourceManager.GetString("ParametroTiempoIntervaloMinutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Servicio fue Detenido.
        /// </summary>
        internal static string ServicioDetenido {
            get {
                return ResourceManager.GetString("ServicioDetenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio fue Iniciado.
        /// </summary>
        internal static string ServicioIniciado {
            get {
                return ResourceManager.GetString("ServicioIniciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Servicio esta Iniciando.
        /// </summary>
        internal static string ServicioIniciando {
            get {
                return ResourceManager.GetString("ServicioIniciando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio fue pausado.
        /// </summary>
        internal static string ServicioPausado {
            get {
                return ResourceManager.GetString("ServicioPausado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Servicio esta  reanudado.
        /// </summary>
        internal static string ServicioReanudado {
            get {
                return ResourceManager.GetString("ServicioReanudado", resourceCulture);
            }
        }
    }
}
