//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAC.Seguridad.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LlavesAplicacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LlavesAplicacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAC.Seguridad.Configuraciones.LlavesAplicacion", typeof(LlavesAplicacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDA004.
        /// </summary>
        internal static string ActualizarAdmControlDual {
            get {
                return ResourceManager.GetString("ActualizarAdmControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRA004.
        /// </summary>
        internal static string ActualizarRol {
            get {
                return ResourceManager.GetString("ActualizarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDA003.
        /// </summary>
        internal static string CatchActualizarAdmControlDual {
            get {
                return ResourceManager.GetString("CatchActualizarAdmControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRA003.
        /// </summary>
        internal static string CatchActualizarRol {
            get {
                return ResourceManager.GetString("CatchActualizarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDA001.
        /// </summary>
        internal static string CatchInsertarAdmControlDual {
            get {
                return ResourceManager.GetString("CatchInsertarAdmControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRA001.
        /// </summary>
        internal static string CatchInsertarRol {
            get {
                return ResourceManager.GetString("CatchInsertarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string EventoAdminitracionControlDual {
            get {
                return ResourceManager.GetString("EventoAdminitracionControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string EventoAdminitracionRoles {
            get {
                return ResourceManager.GetString("EventoAdminitracionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDA002.
        /// </summary>
        internal static string InsertarAdmControlDual {
            get {
                return ResourceManager.GetString("InsertarAdmControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRA002.
        /// </summary>
        internal static string InsertarRol {
            get {
                return ResourceManager.GetString("InsertarRol", resourceCulture);
            }
        }
    }
}
