//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAC.Seguridad.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Parametros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAC.Seguridad.Configuraciones.Parametros", typeof(Parametros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAPwd.
        /// </summary>
        internal static string DAPwd {
            get {
                return ResourceManager.GetString("DAPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAUser.
        /// </summary>
        internal static string DAUser {
            get {
                return ResourceManager.GetString("DAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&amp;(SAMAccountName={0})(objectclass=user)(description={1})).
        /// </summary>
        internal static string FiltroConCedula {
            get {
                return ResourceManager.GetString("FiltroConCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMAccountName.
        /// </summary>
        internal static string FiltroDirectorio {
            get {
                return ResourceManager.GetString("FiltroDirectorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SAMAccountName={0}).
        /// </summary>
        internal static string FiltroId {
            get {
                return ResourceManager.GetString("FiltroId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string GrupoAplicacion {
            get {
                return ResourceManager.GetString("GrupoAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -G.
        /// </summary>
        internal static string GruposBusqueda1 {
            get {
                return ResourceManager.GetString("GruposBusqueda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -U.
        /// </summary>
        internal static string GruposBusqueda2 {
            get {
                return ResourceManager.GetString("GruposBusqueda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -L.
        /// </summary>
        internal static string GruposBusqueda3 {
            get {
                return ResourceManager.GetString("GruposBusqueda3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string IdTipoMensajeInformativo {
            get {
                return ResourceManager.GetString("IdTipoMensajeInformativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP.
        /// </summary>
        internal static string lDAP {
            get {
                return ResourceManager.GetString("lDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string NoExisteOficina {
            get {
                return ResourceManager.GetString("NoExisteOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memberOf.
        /// </summary>
        internal static string PropiedadBusqueda {
            get {
                return ResourceManager.GetString("PropiedadBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        internal static string PropiedadDirectorio1 {
            get {
                return ResourceManager.GetString("PropiedadDirectorio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberOf.
        /// </summary>
        internal static string PropiedadDirectorio2 {
            get {
                return ResourceManager.GetString("PropiedadDirectorio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string PropiedadDirectorio3 {
            get {
                return ResourceManager.GetString("PropiedadDirectorio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to givenname.
        /// </summary>
        internal static string PropiedadDirectorio4 {
            get {
                return ResourceManager.GetString("PropiedadDirectorio4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.
        /// </summary>
        internal static string PropiedadDirectorio5 {
            get {
                return ResourceManager.GetString("PropiedadDirectorio5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        internal static string PropiedadDirectorio6 {
            get {
                return ResourceManager.GetString("PropiedadDirectorio6", resourceCulture);
            }
        }
    }
}
