//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Aplicacion.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LlavesAplicacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LlavesAplicacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Aplicacion.Configuraciones.LlavesAplicacion", typeof(LlavesAplicacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAP-001.
        /// </summary>
        public static string ActualizaArchivoPlano {
            get {
                return ResourceManager.GetString("ActualizaArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA-001.
        /// </summary>
        public static string ActualizaAseguradora {
            get {
                return ResourceManager.GetString("ActualizaAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA004.
        /// </summary>
        public static string ActualizarAprobacionDual {
            get {
                return ResourceManager.GetString("ActualizarAprobacionDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACN001.
        /// </summary>
        public static string ActualizarCausalNovedad {
            get {
                return ResourceManager.GetString("ActualizarCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP003.
        /// </summary>
        public static string ActualizarProductoSatisfactorio {
            get {
                return ResourceManager.GetString("ActualizarProductoSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAA-001.
        /// </summary>
        public static string AseguradoraExisteInsertar {
            get {
                return ResourceManager.GetString("AseguradoraExisteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA-002.
        /// </summary>
        public static string AseguradoraNoActualiza {
            get {
                return ResourceManager.GetString("AseguradoraNoActualiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACVA-002.
        /// </summary>
        public static string CanalVentaActualizado {
            get {
                return ResourceManager.GetString("CanalVentaActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICVA-001.
        /// </summary>
        public static string CanalVentaExisteInsertar {
            get {
                return ResourceManager.GetString("CanalVentaExisteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICVA-002.
        /// </summary>
        public static string CanalVentaGuardado {
            get {
                return ResourceManager.GetString("CanalVentaGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACVA-001.
        /// </summary>
        public static string CanalVentaNoActualizado {
            get {
                return ResourceManager.GetString("CanalVentaNoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA-003.
        /// </summary>
        public static string CatchActualizaAseguradora {
            get {
                return ResourceManager.GetString("CatchActualizaAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA003.
        /// </summary>
        public static string CatchActualizarAprobacionDual {
            get {
                return ResourceManager.GetString("CatchActualizarAprobacionDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAP-003.
        /// </summary>
        public static string CatchActualizarArchivoPlano {
            get {
                return ResourceManager.GetString("CatchActualizarArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACN002.
        /// </summary>
        public static string CatchActualizarCausalNovedad {
            get {
                return ResourceManager.GetString("CatchActualizarCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN-003.
        /// </summary>
        public static string CatchActualizarNovedad {
            get {
                return ResourceManager.GetString("CatchActualizarNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACVA-003.
        /// </summary>
        public static string CatchCanalVentaActualizar {
            get {
                return ResourceManager.GetString("CatchCanalVentaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICVA-003.
        /// </summary>
        public static string CatchCanalVentaInsertar {
            get {
                return ResourceManager.GetString("CatchCanalVentaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP-003.
        /// </summary>
        public static string CatchEliminarArchivoPlano {
            get {
                return ResourceManager.GetString("CatchEliminarArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA001.
        /// </summary>
        public static string CatchEliminarPlantilla {
            get {
                return ResourceManager.GetString("CatchEliminarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA004.
        /// </summary>
        public static string CatchGenerarPlantilla {
            get {
                return ResourceManager.GetString("CatchGenerarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPROG-003.
        /// </summary>
        public static string CatchGuardarProgramacionPlano {
            get {
                return ResourceManager.GetString("CatchGuardarProgramacionPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAA-003.
        /// </summary>
        public static string CatchInsertaAseguradora {
            get {
                return ResourceManager.GetString("CatchInsertaAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA001.
        /// </summary>
        public static string CatchInsertarAprobacionDual {
            get {
                return ResourceManager.GetString("CatchInsertarAprobacionDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICN003.
        /// </summary>
        public static string CatchInsertarCausalNovedad {
            get {
                return ResourceManager.GetString("CatchInsertarCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIPC-003.
        /// </summary>
        public static string CatchInsertarIPC {
            get {
                return ResourceManager.GetString("CatchInsertarIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN-003.
        /// </summary>
        public static string CatchInsertarNovedad {
            get {
                return ResourceManager.GetString("CatchInsertarNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APA-002.
        /// </summary>
        public static string CatchParametroActualizar {
            get {
                return ResourceManager.GetString("CatchParametroActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA-003.
        /// </summary>
        public static string CatchParametroInsertar {
            get {
                return ResourceManager.GetString("CatchParametroInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA003.
        /// </summary>
        public static string CatchPrevisualizarPlantilla {
            get {
                return ResourceManager.GetString("CatchPrevisualizarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CLI001.
        /// </summary>
        public static string ClienteEnListasInhibitorias {
            get {
                return ResourceManager.GetString("ClienteEnListasInhibitorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CIC002.
        /// </summary>
        public static string COBIS_ClienteSinDatosActualizados {
            get {
                return ResourceManager.GetString("COBIS_ClienteSinDatosActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CIC003.
        /// </summary>
        public static string COBIS_ClienteSinInformacion {
            get {
                return ResourceManager.GetString("COBIS_ClienteSinInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CRC001.
        /// </summary>
        public static string COBIS_CreacionClienteEntidadVacia {
            get {
                return ResourceManager.GetString("COBIS_CreacionClienteEntidadVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CELI001.
        /// </summary>
        public static string COBIS_ExepcionCELI {
            get {
                return ResourceManager.GetString("COBIS_ExepcionCELI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CIC001.
        /// </summary>
        public static string COBIS_ExepcionCIC {
            get {
                return ResourceManager.GetString("COBIS_ExepcionCIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CPB001.
        /// </summary>
        public static string COBIS_ExepcionCPB {
            get {
                return ResourceManager.GetString("COBIS_ExepcionCPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-CRC002.
        /// </summary>
        public static string COBIS_ExepcionCRC {
            get {
                return ResourceManager.GetString("COBIS_ExepcionCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-GC001.
        /// </summary>
        public static string COBIS_ExepcionGC {
            get {
                return ResourceManager.GetString("COBIS_ExepcionGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-GD001.
        /// </summary>
        public static string COBIS_ExepcionGD {
            get {
                return ResourceManager.GetString("COBIS_ExepcionGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB-001.
        /// </summary>
        public static string COBIS_SinDetalleMensaje {
            get {
                return ResourceManager.GetString("COBIS_SinDetalleMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP-001.
        /// </summary>
        public static string EliminarArchivoPlanoOK {
            get {
                return ResourceManager.GetString("EliminarArchivoPlanoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAP-002.
        /// </summary>
        public static string ErrorActualizaArchivoPlano {
            get {
                return ResourceManager.GetString("ErrorActualizaArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP002.
        /// </summary>
        public static string ErrorActualizarProducto {
            get {
                return ResourceManager.GetString("ErrorActualizarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAL001.
        /// </summary>
        public static string ErrorAPILista {
            get {
                return ResourceManager.GetString("ErrorAPILista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAS001.
        /// </summary>
        public static string ErrorAPISeguridad {
            get {
                return ResourceManager.GetString("ErrorAPISeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP-002.
        /// </summary>
        public static string ErrorEliminarArchivoPlano {
            get {
                return ResourceManager.GetString("ErrorEliminarArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP002.
        /// </summary>
        public static string ErrorGuardarProducto {
            get {
                return ResourceManager.GetString("ErrorGuardarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        public static string EventoActualizarArchivoPlano {
            get {
                return ResourceManager.GetString("EventoActualizarArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string EventoActualizarCausalNovedad {
            get {
                return ResourceManager.GetString("EventoActualizarCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string EventoActualizarItemMaestra {
            get {
                return ResourceManager.GetString("EventoActualizarItemMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        public static string EventoActualizarMaestra {
            get {
                return ResourceManager.GetString("EventoActualizarMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string EventoActualizarParametro {
            get {
                return ResourceManager.GetString("EventoActualizarParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        public static string EventoActualizarProducto {
            get {
                return ResourceManager.GetString("EventoActualizarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        public static string EventoActualizarVariableProducto {
            get {
                return ResourceManager.GetString("EventoActualizarVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string EventoConsultarVentaBuscarPolizaCliente {
            get {
                return ResourceManager.GetString("EventoConsultarVentaBuscarPolizaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string EventoControlDual {
            get {
                return ResourceManager.GetString("EventoControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        public static string EventoEliminarArchivoPlano {
            get {
                return ResourceManager.GetString("EventoEliminarArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string EventoEliminarItemMaestra {
            get {
                return ResourceManager.GetString("EventoEliminarItemMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        public static string EventoEliminarMaestra {
            get {
                return ResourceManager.GetString("EventoEliminarMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string EventoEliminarVariableProducto {
            get {
                return ResourceManager.GetString("EventoEliminarVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string EventoGuardarCausalNovedad {
            get {
                return ResourceManager.GetString("EventoGuardarCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string EventoGuardarProducto {
            get {
                return ResourceManager.GetString("EventoGuardarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        public static string EventoGuardarProgramacionPlano {
            get {
                return ResourceManager.GetString("EventoGuardarProgramacionPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        public static string EventoInsertarItemMaestra {
            get {
                return ResourceManager.GetString("EventoInsertarItemMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string EventoInsertarMaestra {
            get {
                return ResourceManager.GetString("EventoInsertarMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string EventoInsertarVariableProducto {
            get {
                return ResourceManager.GetString("EventoInsertarVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string EventoParametrizacionAseguradoraInsertar {
            get {
                return ResourceManager.GetString("EventoParametrizacionAseguradoraInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string EventoParametrizacionCanalVenta {
            get {
                return ResourceManager.GetString("EventoParametrizacionCanalVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string EventoParametrizacionGeneral {
            get {
                return ResourceManager.GetString("EventoParametrizacionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string EventoParametrizacionMensajeActualizarMensaje {
            get {
                return ResourceManager.GetString("EventoParametrizacionMensajeActualizarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string EventoParametrizacionMensajesConsultarMensaje {
            get {
                return ResourceManager.GetString("EventoParametrizacionMensajesConsultarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string EventoParametrizacionMensajesGuardaMensaje {
            get {
                return ResourceManager.GetString("EventoParametrizacionMensajesGuardaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string EventoParametrizacionPlantilla {
            get {
                return ResourceManager.GetString("EventoParametrizacionPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string EventoParametrizarAseguradoraActualizar {
            get {
                return ResourceManager.GetString("EventoParametrizarAseguradoraActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string EventoParametrizarCanalVentaActualizar {
            get {
                return ResourceManager.GetString("EventoParametrizarCanalVentaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string EventoParametrizarIPCGuardar {
            get {
                return ResourceManager.GetString("EventoParametrizarIPCGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string EventoParametrizarNovedadActualizar {
            get {
                return ResourceManager.GetString("EventoParametrizarNovedadActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string EventoParametrizarNovedadInsertar {
            get {
                return ResourceManager.GetString("EventoParametrizarNovedadInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string EventoRegistrarVentaConsultarCliente {
            get {
                return ResourceManager.GetString("EventoRegistrarVentaConsultarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string EventoRegistrarVentaConsultarProductosBancarios {
            get {
                return ResourceManager.GetString("EventoRegistrarVentaConsultarProductosBancarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string EventoRegistrarVentaCrearConyuge {
            get {
                return ResourceManager.GetString("EventoRegistrarVentaCrearConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string EventoRegistrarVentaGuardar {
            get {
                return ResourceManager.GetString("EventoRegistrarVentaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string EventoReimpresionPlantilla {
            get {
                return ResourceManager.GetString("EventoReimpresionPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM002.
        /// </summary>
        public static string ExcepcionActualizarItemMaestra {
            get {
                return ResourceManager.GetString("ExcepcionActualizarItemMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMA002.
        /// </summary>
        public static string ExcepcionActualizarMaestra {
            get {
                return ResourceManager.GetString("ExcepcionActualizarMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM-001.
        /// </summary>
        public static string ExcepcionActualizarMensaje {
            get {
                return ResourceManager.GetString("ExcepcionActualizarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP001.
        /// </summary>
        public static string ExcepcionActualizarProducto {
            get {
                return ResourceManager.GetString("ExcepcionActualizarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVV003.
        /// </summary>
        public static string ExcepcionActualizaVariableProducto {
            get {
                return ResourceManager.GetString("ExcepcionActualizaVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM-001.
        /// </summary>
        public static string ExcepcionConsultarMensajes {
            get {
                return ResourceManager.GetString("ExcepcionConsultarMensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIM003.
        /// </summary>
        public static string ExcepcionEliminarItemMaestra {
            get {
                return ResourceManager.GetString("ExcepcionEliminarItemMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PME003.
        /// </summary>
        public static string ExcepcionEliminarMaestra {
            get {
                return ResourceManager.GetString("ExcepcionEliminarMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVV003.
        /// </summary>
        public static string ExcepcionEliminarVariableProducto {
            get {
                return ResourceManager.GetString("ExcepcionEliminarVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIM003.
        /// </summary>
        public static string ExcepcionGuardarItemMaestra {
            get {
                return ResourceManager.GetString("ExcepcionGuardarItemMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMI003.
        /// </summary>
        public static string ExcepcionGuardarMaestra {
            get {
                return ResourceManager.GetString("ExcepcionGuardarMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM-001.
        /// </summary>
        public static string ExcepcionGuardarMensaje {
            get {
                return ResourceManager.GetString("ExcepcionGuardarMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP001.
        /// </summary>
        public static string ExcepcionGuardarProducto {
            get {
                return ResourceManager.GetString("ExcepcionGuardarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVV003.
        /// </summary>
        public static string ExcepcionInsertaVariableProducto {
            get {
                return ResourceManager.GetString("ExcepcionInsertaVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP003.
        /// </summary>
        public static string GuardarProductoSatisfactorio {
            get {
                return ResourceManager.GetString("GuardarProductoSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPROG-001.
        /// </summary>
        public static string GuardarProgramacionPlano {
            get {
                return ResourceManager.GetString("GuardarProgramacionPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAA-002.
        /// </summary>
        public static string InsertarAseguradora {
            get {
                return ResourceManager.GetString("InsertarAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICN001.
        /// </summary>
        public static string InsertarCausalNovedad {
            get {
                return ResourceManager.GetString("InsertarCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICN002.
        /// </summary>
        public static string InsertarCausalNovedadNoExitoso {
            get {
                return ResourceManager.GetString("InsertarCausalNovedadNoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIPC-001.
        /// </summary>
        public static string InsertarIPC {
            get {
                return ResourceManager.GetString("InsertarIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIPC-002.
        /// </summary>
        public static string InsertarIPCNoExitoso {
            get {
                return ResourceManager.GetString("InsertarIPCNoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN-001.
        /// </summary>
        public static string InsertarNovedad {
            get {
                return ResourceManager.GetString("InsertarNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM001.
        /// </summary>
        public static string ItemMaestraActualizado {
            get {
                return ResourceManager.GetString("ItemMaestraActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIM001.
        /// </summary>
        public static string ItemMaestraEliminado {
            get {
                return ResourceManager.GetString("ItemMaestraEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIM002.
        /// </summary>
        public static string ItemMaestraExiste {
            get {
                return ResourceManager.GetString("ItemMaestraExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIM001.
        /// </summary>
        public static string ItemMaestraGuardado {
            get {
                return ResourceManager.GetString("ItemMaestraGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIM002.
        /// </summary>
        public static string ItemMaestraUsadoVenta {
            get {
                return ResourceManager.GetString("ItemMaestraUsadoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMA001.
        /// </summary>
        public static string MaestraActualizada {
            get {
                return ResourceManager.GetString("MaestraActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PME001.
        /// </summary>
        public static string MaestraEliminada {
            get {
                return ResourceManager.GetString("MaestraEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMI002.
        /// </summary>
        public static string MaestraExiste {
            get {
                return ResourceManager.GetString("MaestraExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMI001.
        /// </summary>
        public static string MaestraGuardada {
            get {
                return ResourceManager.GetString("MaestraGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PME002.
        /// </summary>
        public static string MaestraUsadaVenta {
            get {
                return ResourceManager.GetString("MaestraUsadaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM-002.
        /// </summary>
        public static string MensajeActualizado {
            get {
                return ResourceManager.GetString("MensajeActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM-002.
        /// </summary>
        public static string MensajeGuardado {
            get {
                return ResourceManager.GetString("MensajeGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIM004.
        /// </summary>
        public static string MinimoItemsMaestraSuperado {
            get {
                return ResourceManager.GetString("MinimoItemsMaestraSuperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPROG-002.
        /// </summary>
        public static string NoGuardaProgramacionPlano {
            get {
                return ResourceManager.GetString("NoGuardaProgramacionPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN-001.
        /// </summary>
        public static string NovedadActualizada {
            get {
                return ResourceManager.GetString("NovedadActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN-002.
        /// </summary>
        public static string NovedadExisteInsertar {
            get {
                return ResourceManager.GetString("NovedadExisteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN-002.
        /// </summary>
        public static string NovedadNoActualiza {
            get {
                return ResourceManager.GetString("NovedadNoActualiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APA-001.
        /// </summary>
        public static string ParametroActualizado {
            get {
                return ResourceManager.GetString("ParametroActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA-001.
        /// </summary>
        public static string ParametroExisteInsertar {
            get {
                return ResourceManager.GetString("ParametroExisteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA-002.
        /// </summary>
        public static string ParametroGuardadoInsertar {
            get {
                return ResourceManager.GetString("ParametroGuardadoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA002.
        /// </summary>
        public static string PlantillaActivada {
            get {
                return ResourceManager.GetString("PlantillaActivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA002.
        /// </summary>
        public static string RegistroTemporalAlmacenado {
            get {
                return ResourceManager.GetString("RegistroTemporalAlmacenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVV001.
        /// </summary>
        public static string VariableProductoActualizada {
            get {
                return ResourceManager.GetString("VariableProductoActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVV001.
        /// </summary>
        public static string VariableProductoEliminada {
            get {
                return ResourceManager.GetString("VariableProductoEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVV002.
        /// </summary>
        public static string VariableProductoExisteActualizacion {
            get {
                return ResourceManager.GetString("VariableProductoExisteActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVV002.
        /// </summary>
        public static string VariableProductoExisteEliminacion {
            get {
                return ResourceManager.GetString("VariableProductoExisteEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVV002.
        /// </summary>
        public static string VariableProductoExisteInsercion {
            get {
                return ResourceManager.GetString("VariableProductoExisteInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVV001.
        /// </summary>
        public static string VariableProductoInsertada {
            get {
                return ResourceManager.GetString("VariableProductoInsertada", resourceCulture);
            }
        }
    }
}
