//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Aplicacion.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Aplicacion.Configuraciones.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBIS.
        /// </summary>
        internal static string COBIS {
            get {
                return ResourceManager.GetString("COBIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del producto ya existe en el sistema.
        /// </summary>
        internal static string CodigoSeguroExiste {
            get {
                return ResourceManager.GetString("CodigoSeguroExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Cobis - {0} - {1}.
        /// </summary>
        internal static string ErrorCobis {
            get {
                return ResourceManager.GetString("ErrorCobis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al consultar servicio COBIS.
        /// </summary>
        internal static string ErrorConvenio {
            get {
                return ResourceManager.GetString("ErrorConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ingresó el seguro, por favor intente de nuevo. Detalle: {0}.
        /// </summary>
        internal static string ErrorInsertarSeguro {
            get {
                return ResourceManager.GetString("ErrorInsertarSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Interno {0}.
        /// </summary>
        internal static string ErrorInterno {
            get {
                return ResourceManager.GetString("ErrorInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado la ruta del servicio de Transaccion.
        /// </summary>
        internal static string ErrorNoConfiguradoRutaServicioTransaccion {
            get {
                return ResourceManager.GetString("ErrorNoConfiguradoRutaServicioTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ingreso el seguro con éxito..
        /// </summary>
        internal static string ExitoInsertarSeguro {
            get {
                return ResourceManager.GetString("ExitoInsertarSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje no parametrizado.
        /// </summary>
        internal static string MensajeNoParametrizado {
            get {
                return ResourceManager.GetString("MensajeNoParametrizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de ventas excede las permitidas para diferentes cuentas.
        /// </summary>
        internal static string NumeroCuentas {
            get {
                return ResourceManager.GetString("NumeroCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de ventas excede las permitidas para una misma cuenta.
        /// </summary>
        internal static string NumeroVentas {
            get {
                return ResourceManager.GetString("NumeroVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe asociar por lo menos un canal de venta&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroCanalesVenta {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroCanalesVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un código para el seguro&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroCodigo {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un convenio de la aseguradora&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroConvenio {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una descripción para el seguro&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroDescripcion {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La edad máxima del conyuge debe estar entre 1 y 66&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroEdadMaximaConyuge {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroEdadMaximaConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La edad mínima del conyuge debe estar entre 1 y 66&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroEdadMinimaConyuge {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroEdadMinimaConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La edad mínima no debe ser mayor a la edad maxíma parametrizada para el conyuge&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroEdadMinimaMaximaConyuge {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroEdadMinimaMaximaConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una aseguradora&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroIdAseguradora {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroIdAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un nombre para el seguro&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroNombreSeguro {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroNombreSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los beneficiarios no puede ser cero&lt;/br&gt; .
        /// </summary>
        internal static string ParametrizacionSeguroNumeroBeneficiarios {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroNumeroBeneficiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número máximo de ventas de este seguro por cliente no debe ser cero&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroNumeroMaximoSegurosCliente {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroNumeroMaximoSegurosCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número máximo de ventas de este seguro por cada cuenta de cliente no debe ser cero&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroNumeroMaximoSegurosPorCuentaCliente {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroNumeroMaximoSegurosPorCuentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar por lo menos un plan&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroPlanes {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroPlanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar por lo menos uno de los tipos de identificacion&lt;/br&gt;.
        /// </summary>
        internal static string ParametrizacionSeguroTiposIdentificacion {
            get {
                return ResourceManager.GetString("ParametrizacionSeguroTiposIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas Generando la Poliza.
        /// </summary>
        internal static string PolizaGuardarError {
            get {
                return ResourceManager.GetString("PolizaGuardarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Genero con exito la Poliza {0}.
        /// </summary>
        internal static string PolizaGuardarExito {
            get {
                return ResourceManager.GetString("PolizaGuardarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronización Catalogos: .
        /// </summary>
        internal static string SincronizacionCatalogos {
            get {
                return ResourceManager.GetString("SincronizacionCatalogos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronización Dias Habiles: .
        /// </summary>
        internal static string SincronizacionDias {
            get {
                return ResourceManager.GetString("SincronizacionDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy {0} mas los dias de anticipo {1} es igual al {2} la cual no es la fecha control {3}.
        /// </summary>
        internal static string SinCumplimientoParametros {
            get {
                return ResourceManager.GetString("SinCumplimientoParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin datos en la consulta a Cobis {0} .
        /// </summary>
        internal static string SinDTO {
            get {
                return ResourceManager.GetString("SinDTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Errores en los canales de venta&lt;/h4&gt;&lt;/br&gt;.
        /// </summary>
        internal static string SubtituloErroresCanalesVentaSeguro {
            get {
                return ResourceManager.GetString("SubtituloErroresCanalesVentaSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Errores en los planes&lt;/h4&gt;&lt;/br&gt;.
        /// </summary>
        internal static string SubtituloErroresPlanesSeguro {
            get {
                return ResourceManager.GetString("SubtituloErroresPlanesSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Errores en los productos no permitidos&lt;/h4&gt;&lt;/br&gt;.
        /// </summary>
        internal static string SubtituloErroresProductosNoPermitidosSeguro {
            get {
                return ResourceManager.GetString("SubtituloErroresProductosNoPermitidosSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Errores en los tipos de identificación&lt;/h4&gt;&lt;/br&gt;.
        /// </summary>
        internal static string SubtituloErroresTiposIdentificacionSeguro {
            get {
                return ResourceManager.GetString("SubtituloErroresTiposIdentificacionSeguro", resourceCulture);
            }
        }
    }
}
