//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Aplicacion.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Parametros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Aplicacion.Configuraciones.Parametros", typeof(Parametros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string ClienteSinDatosActualizados {
            get {
                return ResourceManager.GetString("ClienteSinDatosActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 253.
        /// </summary>
        internal static string CobisCodigoCausalTransaccion {
            get {
                return ResourceManager.GetString("CobisCodigoCausalTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBISConsultarInformacionCliente.
        /// </summary>
        internal static string COBISConsultarInformacionCliente {
            get {
                return ResourceManager.GetString("COBISConsultarInformacionCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string CobisEstadoCuentas {
            get {
                return ResourceManager.GetString("CobisEstadoCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 444100400017.
        /// </summary>
        internal static string CobisNumeroAprobacionExterno {
            get {
                return ResourceManager.GetString("CobisNumeroAprobacionExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CobisProcesoOriginadorGenerarDebito {
            get {
                return ResourceManager.GetString("CobisProcesoOriginadorGenerarDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CobisRespuestaSatisfactoria {
            get {
                return ResourceManager.GetString("CobisRespuestaSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string CobisTipoCuentaAhorros {
            get {
                return ResourceManager.GetString("CobisTipoCuentaAhorros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoCanalOriginador.
        /// </summary>
        internal static string CodigoCanalOriginador {
            get {
                return ResourceManager.GetString("CodigoCanalOriginador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoCanalOriginadorAPI.
        /// </summary>
        internal static string CodigoCanalOriginadorAPI {
            get {
                return ResourceManager.GetString("CodigoCanalOriginadorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoCanalRecaudo.
        /// </summary>
        internal static string CodigoCanalRecaudo {
            get {
                return ResourceManager.GetString("CodigoCanalRecaudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;9&quot;.
        /// </summary>
        internal static string CodigoCardifDefecto {
            get {
                return ResourceManager.GetString("CodigoCardifDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoFormaPagoAHO.
        /// </summary>
        internal static string CodigoFormaPagoAHO {
            get {
                return ResourceManager.GetString("CodigoFormaPagoAHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoFormaPagoCTE.
        /// </summary>
        internal static string CodigoFormaPagoCTE {
            get {
                return ResourceManager.GetString("CodigoFormaPagoCTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoFuncionalidadOriginador.
        /// </summary>
        internal static string CodigoFuncionalidadOriginador {
            get {
                return ResourceManager.GetString("CodigoFuncionalidadOriginador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoFuncionalidadOriginadorAPI.
        /// </summary>
        internal static string CodigoFuncionalidadOriginadorAPI {
            get {
                return ResourceManager.GetString("CodigoFuncionalidadOriginadorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoProcesoOriginador.
        /// </summary>
        internal static string CodigoProcesoOriginador {
            get {
                return ResourceManager.GetString("CodigoProcesoOriginador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoProcesoOriginadorAPI.
        /// </summary>
        internal static string CodigoProcesoOriginadorAPI {
            get {
                return ResourceManager.GetString("CodigoProcesoOriginadorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string CodigoProductoAhorro {
            get {
                return ResourceManager.GetString("CodigoProductoAhorro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CodigoProductoCorriente {
            get {
                return ResourceManager.GetString("CodigoProductoCorriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoTipoProductoAHO.
        /// </summary>
        internal static string CodigoTipoProductoAHO {
            get {
                return ResourceManager.GetString("CodigoTipoProductoAHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoTipoProductoCTE.
        /// </summary>
        internal static string CodigoTipoProductoCTE {
            get {
                return ResourceManager.GetString("CodigoTipoProductoCTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codTipoRespuesta.
        /// </summary>
        internal static string codTipoRespuesta {
            get {
                return ResourceManager.GetString("codTipoRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsultarProductosBancarios.
        /// </summary>
        internal static string ConsultarProductosBancarios {
            get {
                return ResourceManager.GetString("ConsultarProductosBancarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreacionRapidaCliente.
        /// </summary>
        internal static string CreacionRapidaCliente {
            get {
                return ResourceManager.GetString("CreacionRapidaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditoAseguradoraCodigoProducto.
        /// </summary>
        internal static string CreditoAseguradoraCodigoProducto {
            get {
                return ResourceManager.GetString("CreditoAseguradoraCodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditoAseguradoraIdentificacion.
        /// </summary>
        internal static string CreditoAseguradoraIdentificacion {
            get {
                return ResourceManager.GetString("CreditoAseguradoraIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditoAseguradoraNumeroCuenta.
        /// </summary>
        internal static string CreditoAseguradoraNumeroCuenta {
            get {
                return ResourceManager.GetString("CreditoAseguradoraNumeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditoAseguradoraTipoIdentificacion.
        /// </summary>
        internal static string CreditoAseguradoraTipoIdentificacion {
            get {
                return ResourceManager.GetString("CreditoAseguradoraTipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatosPolizaDocumento.
        /// </summary>
        internal static string DatosPolizaDocumento {
            get {
                return ResourceManager.GetString("DatosPolizaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiasAAnticipar.
        /// </summary>
        internal static string DiasAAnticipar {
            get {
                return ResourceManager.GetString("DiasAAnticipar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiasALlenar.
        /// </summary>
        internal static string DiasALlenar {
            get {
                return ResourceManager.GetString("DiasALlenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string EstadoActivoCobis {
            get {
                return ResourceManager.GetString("EstadoActivoCobis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string EstadoCatalogo {
            get {
                return ResourceManager.GetString("EstadoCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaControlSistema.
        /// </summary>
        internal static string FechaControlSistema {
            get {
                return ResourceManager.GetString("FechaControlSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecTransaccion.
        /// </summary>
        internal static string fecTransaccion {
            get {
                return ResourceManager.GetString("fecTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FecTransaccionAPI.
        /// </summary>
        internal static string FecTransaccionAPI {
            get {
                return ResourceManager.GetString("FecTransaccionAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm:ss.
        /// </summary>
        internal static string Formatohhmmss {
            get {
                return ResourceManager.GetString("Formatohhmmss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerarCreditoACuentaAseguradora.
        /// </summary>
        internal static string GenerarCreditoACuentaAseguradora {
            get {
                return ResourceManager.GetString("GenerarCreditoACuentaAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerarDebitoACuentaCliente.
        /// </summary>
        internal static string GenerarDebitoACuentaCliente {
            get {
                return ResourceManager.GetString("GenerarDebitoACuentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerarRecaudo.
        /// </summary>
        internal static string GenerarRecaudo {
            get {
                return ResourceManager.GetString("GenerarRecaudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identificadorTransaccion.
        /// </summary>
        internal static string identificadorTransaccion {
            get {
                return ResourceManager.GetString("identificadorTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentificadorTransaccional.
        /// </summary>
        internal static string IdentificadorTransaccional {
            get {
                return ResourceManager.GetString("IdentificadorTransaccional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentificadorTransaccionalAPI.
        /// </summary>
        internal static string IdentificadorTransaccionalAPI {
            get {
                return ResourceManager.GetString("IdentificadorTransaccionalAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string IdMensajerError {
            get {
                return ResourceManager.GetString("IdMensajerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipConsumidor.
        /// </summary>
        internal static string ipConsumidor {
            get {
                return ResourceManager.GetString("ipConsumidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipConsumidorAPI.
        /// </summary>
        internal static string ipConsumidorAPI {
            get {
                return ResourceManager.GetString("ipConsumidorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpRealizarNotaDebito.
        /// </summary>
        internal static string MetodoOpRealizarNotaDebito {
            get {
                return ResourceManager.GetString("MetodoOpRealizarNotaDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombiana.
        /// </summary>
        internal static string Nacionalidad {
            get {
                return ResourceManager.GetString("Nacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string NumeroTres {
            get {
                return ResourceManager.GetString("NumeroTres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpRealizarNotaCredito.
        /// </summary>
        internal static string OpRealizarNotaCredito {
            get {
                return ResourceManager.GetString("OpRealizarNotaCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200.
        /// </summary>
        internal static string ParametroPaginacionCobis {
            get {
                return ResourceManager.GetString("ParametroPaginacionCobis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        internal static string POST {
            get {
                return ResourceManager.GetString("POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string RegristroGuardadoBD {
            get {
                return ResourceManager.GetString("RegristroGuardadoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RutaServicioTransaccion.
        /// </summary>
        internal static string RutaServicioTransaccion {
            get {
                return ResourceManager.GetString("RutaServicioTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paginacion.
        /// </summary>
        internal static string TamanoPaginacionCobis {
            get {
                return ResourceManager.GetString("TamanoPaginacionCobis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valDescripcionRespuesta.
        /// </summary>
        internal static string valDescripcionRespuesta {
            get {
                return ResourceManager.GetString("valDescripcionRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string VersionDocumento {
            get {
                return ResourceManager.GetString("VersionDocumento", resourceCulture);
            }
        }
    }
}
