//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Aplicacion.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XML_RequestCobis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XML_RequestCobis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Aplicacion.Configuraciones.XML_RequestCobis", typeof(XML_RequestCobis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/soap+xml;charset=UTF-8;action=&quot;http://service.srvaplcobistransaccion.ecobis.cobiscorp.ws/SrvAplCobisTransaccion/{0}/.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codCanalOriginador&gt;{0}&lt;/dto:codCanalOriginador&gt;.
        /// </summary>
        public static string DtoCodCanalOriginador {
            get {
                return ResourceManager.GetString("DtoCodCanalOriginador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codCanalRecaudo&gt;{0}&lt;/dto:codCanalRecaudo&gt;.
        /// </summary>
        public static string DtocodCanalRecaudo {
            get {
                return ResourceManager.GetString("DtocodCanalRecaudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codCausalTransaccion&gt;{0}&lt;/dto:codCausalTransaccion&gt;.
        /// </summary>
        public static string DtoCodCausalTransaccion {
            get {
                return ResourceManager.GetString("DtoCodCausalTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codConvenio&gt;{0}&lt;/dto:codConvenio&gt;.
        /// </summary>
        public static string DtocodConvenio {
            get {
                return ResourceManager.GetString("DtocodConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codFormaPago&gt;{0}&lt;/dto:codFormaPago&gt;.
        /// </summary>
        public static string DtocodFormaPago {
            get {
                return ResourceManager.GetString("DtocodFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codFuncionalidadOriginador&gt;{0}&lt;/dto:codFuncionalidadOriginador&gt;.
        /// </summary>
        public static string DtoCodFuncionalidadOriginador {
            get {
                return ResourceManager.GetString("DtoCodFuncionalidadOriginador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codOficina&gt;{0}&lt;/dto:codOficina&gt;.
        /// </summary>
        public static string DtocodOficina {
            get {
                return ResourceManager.GetString("DtocodOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codProcesoOriginador&gt;{0}&lt;/dto:codProcesoOriginador&gt;.
        /// </summary>
        public static string DtoCodProcesoOriginador {
            get {
                return ResourceManager.GetString("DtoCodProcesoOriginador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codTipoIdentidadPersona&gt;{0}&lt;/dto:codTipoIdentidadPersona&gt;.
        /// </summary>
        public static string DtoCodTipoIdentidadPersona {
            get {
                return ResourceManager.GetString("DtoCodTipoIdentidadPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:codTipoProducto&gt;{0}&lt;/dto:codTipoProducto&gt;.
        /// </summary>
        public static string DtoCodTipoProducto {
            get {
                return ResourceManager.GetString("DtoCodTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:contextoTransaccional&gt;.
        /// </summary>
        public static string DtoContextoTransaccional {
            get {
                return ResourceManager.GetString("DtoContextoTransaccional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:contextoTransaccional&gt;.
        /// </summary>
        public static string DtoContextoTransaccionalCierre {
            get {
                return ResourceManager.GetString("DtoContextoTransaccionalCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:convenio&gt;.
        /// </summary>
        public static string Dtoconvenio {
            get {
                return ResourceManager.GetString("Dtoconvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:convenio&gt;.
        /// </summary>
        public static string DtoconvenioCierre {
            get {
                return ResourceManager.GetString("DtoconvenioCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:cuenta&gt;.
        /// </summary>
        public static string DtoCuenta {
            get {
                return ResourceManager.GetString("DtoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:cuenta&gt;.
        /// </summary>
        public static string DtoCuentaCIerre {
            get {
                return ResourceManager.GetString("DtoCuentaCIerre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:fecTransaccion&gt;{0}&lt;/dto:fecTransaccion&gt;.
        /// </summary>
        public static string DtoFecTransaccion {
            get {
                return ResourceManager.GetString("DtoFecTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:identidadPersona&gt;.
        /// </summary>
        public static string DtoidentidadPersona {
            get {
                return ResourceManager.GetString("DtoidentidadPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:identidadPersona&gt;.
        /// </summary>
        public static string DtoidentidadPersonaCierre {
            get {
                return ResourceManager.GetString("DtoidentidadPersonaCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:identificadorTransaccional&gt;{0}&lt;/dto:identificadorTransaccional&gt;.
        /// </summary>
        public static string DtoIdentificadorTransaccional {
            get {
                return ResourceManager.GetString("DtoIdentificadorTransaccional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:ipConsumidor&gt;{0}&lt;/dto:ipConsumidor&gt;.
        /// </summary>
        public static string DtoIpConsumidor {
            get {
                return ResourceManager.GetString("DtoIpConsumidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:oficina&gt;.
        /// </summary>
        public static string Dtooficina {
            get {
                return ResourceManager.GetString("Dtooficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:oficina&gt;.
        /// </summary>
        public static string DtooficinaCierre {
            get {
                return ResourceManager.GetString("DtooficinaCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:recaudo&gt;.
        /// </summary>
        public static string DtoRecaudo {
            get {
                return ResourceManager.GetString("DtoRecaudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:recaudo&gt;.
        /// </summary>
        public static string DtoRecaudoCierre {
            get {
                return ResourceManager.GetString("DtoRecaudoCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:transaccion&gt;.
        /// </summary>
        public static string DtoTransaccion {
            get {
                return ResourceManager.GetString("DtoTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/dto:transaccion&gt;.
        /// </summary>
        public static string DtoTransaccionCierre {
            get {
                return ResourceManager.GetString("DtoTransaccionCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:valIdentidadPersona&gt;{0}&lt;/dto:valIdentidadPersona&gt;.
        /// </summary>
        public static string DtoValIdentidadPersona {
            get {
                return ResourceManager.GetString("DtoValIdentidadPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:valMonto&gt;{0}&lt;/dto:valMonto&gt;.
        /// </summary>
        public static string DtoValMonto {
            get {
                return ResourceManager.GetString("DtoValMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:valNumAprobacionExterno&gt;{0}&lt;/dto:valNumAprobacionExterno&gt;.
        /// </summary>
        public static string DtoValNumAprobacionExterno {
            get {
                return ResourceManager.GetString("DtoValNumAprobacionExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:valNumeroProducto&gt;{0}&lt;/dto:valNumeroProducto&gt;.
        /// </summary>
        public static string DtoValNumeroProducto {
            get {
                return ResourceManager.GetString("DtoValNumeroProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dto:valReferencia1&gt;{0}&lt;/dto:valReferencia1&gt;.
        /// </summary>
        public static string DtovalReferencia1 {
            get {
                return ResourceManager.GetString("DtovalReferencia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ser:opRealizarNotaCreditoSolicitud&gt;.
        /// </summary>
        public static string SerOpRealizarNotaCreditoSolicitud {
            get {
                return ResourceManager.GetString("SerOpRealizarNotaCreditoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ser:opRealizarNotaCreditoSolicitud&gt;.
        /// </summary>
        public static string SerOpRealizarNotaCreditoSolicitudCierre {
            get {
                return ResourceManager.GetString("SerOpRealizarNotaCreditoSolicitudCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ser:opRealizarNotaDebitoSolicitud&gt;.
        /// </summary>
        public static string SerOpRealizarNotaDebitoSolicitud {
            get {
                return ResourceManager.GetString("SerOpRealizarNotaDebitoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ser:opRealizarNotaDebitoSolicitud&gt;.
        /// </summary>
        public static string SerOpRealizarNotaDebitoSolicitudCierre {
            get {
                return ResourceManager.GetString("SerOpRealizarNotaDebitoSolicitudCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ser:opRealizarRecaudoSolicitud&gt;.
        /// </summary>
        public static string SeropRealizarRecaudoSolicitud {
            get {
                return ResourceManager.GetString("SeropRealizarRecaudoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ser:opRealizarRecaudoSolicitud&gt;.
        /// </summary>
        public static string SeropRealizarRecaudoSolicitudCierre {
            get {
                return ResourceManager.GetString("SeropRealizarRecaudoSolicitudCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAPAction: http://tempuri.org/{0}.
        /// </summary>
        public static string SOAPAction {
            get {
                return ResourceManager.GetString("SOAPAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Body&gt;.
        /// </summary>
        public static string SoapBody {
            get {
                return ResourceManager.GetString("SoapBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/soap:Body&gt;.
        /// </summary>
        public static string SoapBodyCierre {
            get {
                return ResourceManager.GetString("SoapBodyCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:ser=&quot;http://service.srvaplcobistransaccion.ecobis.cobiscorp&quot; xmlns:dto=&quot;http://dto.srvaplcobisentidades.ecobis.cobiscorp&quot;&gt;.
        /// </summary>
        public static string SoapEnvelope {
            get {
                return ResourceManager.GetString("SoapEnvelope", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:ser=&quot;http://service.srvaplcobisconvenio.ecobis.cobiscorp&quot; xmlns:dto=&quot;http://dto.srvaplcobisentidades.ecobis.cobiscorp&quot;&gt;.
        /// </summary>
        public static string SoapEnvelopeRecaudo
        {
            get
            {
                return ResourceManager.GetString("SoapEnvelopeRecaudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/soap:Envelope&gt;.
        /// </summary>
        public static string SoapEnvelopeCerrar {
            get {
                return ResourceManager.GetString("SoapEnvelopeCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Header/&gt;.
        /// </summary>
        public static string SoapHeader {
            get {
                return ResourceManager.GetString("SoapHeader", resourceCulture);
            }
        }
    }
}
