//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSegurosUI.ServicioGenerico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioGenerico.IServicioGenerico")]
    public interface IServicioGenerico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGenerico/ConsultarCatalogo", ReplyAction="http://tempuri.org/IServicioGenerico/ConsultarCatalogoResponse")]
        BancaSeguros.Entidades.Catalogo.DtoCatalogo ConsultarCatalogo(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGenerico/ConsultarCatalogo", ReplyAction="http://tempuri.org/IServicioGenerico/ConsultarCatalogoResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.Catalogo.DtoCatalogo> ConsultarCatalogoAsync(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGenerico/GuardarError", ReplyAction="http://tempuri.org/IServicioGenerico/GuardarErrorResponse")]
        BancaSeguros.Entidades.General.Resultado GuardarError(int evento, string excepcion, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGenerico/GuardarError", ReplyAction="http://tempuri.org/IServicioGenerico/GuardarErrorResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarErrorAsync(int evento, string excepcion, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGenerico/ConsultarMensajePorLlave", ReplyAction="http://tempuri.org/IServicioGenerico/ConsultarMensajePorLlaveResponse")]
        BancaSeguros.Entidades.General.Resultado ConsultarMensajePorLlave(int evento, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGenerico/ConsultarMensajePorLlave", ReplyAction="http://tempuri.org/IServicioGenerico/ConsultarMensajePorLlaveResponse")]
        System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ConsultarMensajePorLlaveAsync(int evento, string llave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGenericoChannel : BancaSegurosUI.ServicioGenerico.IServicioGenerico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGenericoClient : System.ServiceModel.ClientBase<BancaSegurosUI.ServicioGenerico.IServicioGenerico>, BancaSegurosUI.ServicioGenerico.IServicioGenerico {
        
        public ServicioGenericoClient() {
        }
        
        public ServicioGenericoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGenericoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGenericoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGenericoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancaSeguros.Entidades.Catalogo.DtoCatalogo ConsultarCatalogo(string NombreTabla) {
            return base.Channel.ConsultarCatalogo(NombreTabla);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.Catalogo.DtoCatalogo> ConsultarCatalogoAsync(string NombreTabla) {
            return base.Channel.ConsultarCatalogoAsync(NombreTabla);
        }
        
        public BancaSeguros.Entidades.General.Resultado GuardarError(int evento, string excepcion, string llave) {
            return base.Channel.GuardarError(evento, excepcion, llave);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> GuardarErrorAsync(int evento, string excepcion, string llave) {
            return base.Channel.GuardarErrorAsync(evento, excepcion, llave);
        }
        
        public BancaSeguros.Entidades.General.Resultado ConsultarMensajePorLlave(int evento, string llave) {
            return base.Channel.ConsultarMensajePorLlave(evento, llave);
        }
        
        public System.Threading.Tasks.Task<BancaSeguros.Entidades.General.Resultado> ConsultarMensajePorLlaveAsync(int evento, string llave) {
            return base.Channel.ConsultarMensajePorLlaveAsync(evento, llave);
        }
    }
}
