//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Repositorio.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Campos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Campos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Repositorio.Configuraciones.Campos", typeof(Campos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abreviatura.
        /// </summary>
        internal static string Abreviatura {
            get {
                return ResourceManager.GetString("Abreviatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accion.
        /// </summary>
        internal static string Accion {
            get {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activa.
        /// </summary>
        internal static string Activa {
            get {
                return ResourceManager.GetString("Activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actividadEconomica.
        /// </summary>
        internal static string actividadEconomica {
            get {
                return ResourceManager.GetString("actividadEconomica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActividadEconomicaCliente.
        /// </summary>
        internal static string ActividadEconomicaCliente {
            get {
                return ResourceManager.GetString("ActividadEconomicaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activo.
        /// </summary>
        internal static string activo {
            get {
                return ResourceManager.GetString("activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activoAseguradora.
        /// </summary>
        internal static string activoAseguradora {
            get {
                return ResourceManager.GetString("activoAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        internal static string Altura {
            get {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anoActual.
        /// </summary>
        internal static string AnoActual {
            get {
                return ResourceManager.GetString("AnoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ano.
        /// </summary>
        internal static string AnoIPC {
            get {
                return ResourceManager.GetString("AnoIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApellidoBeneficiario.
        /// </summary>
        internal static string ApellidoBeneficiario {
            get {
                return ResourceManager.GetString("ApellidoBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuditID.
        /// </summary>
        internal static string AuditID {
            get {
                return ResourceManager.GetString("AuditID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beneficiario.
        /// </summary>
        internal static string beneficiario {
            get {
                return ResourceManager.GetString("beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPOS.
        /// </summary>
        internal static string CampoPoliza {
            get {
                return ResourceManager.GetString("CampoPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camposPlantilla.
        /// </summary>
        internal static string CamposPlantilla {
            get {
                return ResourceManager.GetString("CamposPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanalVenta.
        /// </summary>
        internal static string CanalVenta {
            get {
                return ResourceManager.GetString("CanalVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celular.
        /// </summary>
        internal static string celular {
            get {
                return ResourceManager.GetString("celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CelularCliente.
        /// </summary>
        internal static string CelularCliente {
            get {
                return ResourceManager.GetString("CelularCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ciudadNacimiento.
        /// </summary>
        internal static string ciudadNacimiento {
            get {
                return ResourceManager.GetString("ciudadNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiudadNacimientoCliente.
        /// </summary>
        internal static string CiudadNacimientoCliente {
            get {
                return ResourceManager.GetString("CiudadNacimientoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiudadNacimientoConyuge.
        /// </summary>
        internal static string CiudadNacimientoConyuge {
            get {
                return ResourceManager.GetString("CiudadNacimientoConyuge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ciudad.
        /// </summary>
        internal static string ciudad
        {
            get
            {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CiudadOficina.
        /// </summary>
        internal static string CiudadOficina {
            get {
                return ResourceManager.GetString("CiudadOficina", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ciudadResidencia.
        /// </summary>
        internal static string ciudadResidencia {
            get {
                return ResourceManager.GetString("ciudadResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiudadResidenciaCliente.
        /// </summary>
        internal static string CiudadResidenciaCliente {
            get {
                return ResourceManager.GetString("CiudadResidenciaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiudadResidenciaConyuge.
        /// </summary>
        internal static string CiudadResidenciaConyuge {
            get {
                return ResourceManager.GetString("CiudadResidenciaConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigo.
        /// </summary>
        internal static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoAsesor.
        /// </summary>
        internal static string CodigoAsesor {
            get {
                return ResourceManager.GetString("CodigoAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoCardif.
        /// </summary>
        internal static string CodigoCardif {
            get {
                return ResourceManager.GetString("CodigoCardif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoCategoria.
        /// </summary>
        internal static string codigoCategoria {
            get {
                return ResourceManager.GetString("codigoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoCausalNovedadNegocio.
        /// </summary>
        internal static string CodigoCausalNovedad {
            get {
                return ResourceManager.GetString("CodigoCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoConvenio.
        /// </summary>
        internal static string codigoConvenio {
            get {
                return ResourceManager.GetString("codigoConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoGrupo.
        /// </summary>
        internal static string codigoGrupo {
            get {
                return ResourceManager.GetString("codigoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoTipoNovedad.
        /// </summary>
        internal static string CodigoNovedad {
            get {
                return ResourceManager.GetString("CodigoNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoOficina.
        /// </summary>
        internal static string CodigoOficina {
            get {
                return ResourceManager.GetString("CodigoOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoPlan.
        /// </summary>
        internal static string CodigoPlan {
            get {
                return ResourceManager.GetString("CodigoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoProducto.
        /// </summary>
        internal static string codigoProducto {
            get {
                return ResourceManager.GetString("codigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoSubProducto.
        /// </summary>
        internal static string codigoSubProducto {
            get {
                return ResourceManager.GetString("codigoSubProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoSuperintendencia.
        /// </summary>
        internal static string codigoSuperintendencia {
            get {
                return ResourceManager.GetString("codigoSuperintendencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoTipoCuenta.
        /// </summary>
        internal static string CodigoTipoCuenta {
            get {
                return ResourceManager.GetString("CodigoTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutivo.
        /// </summary>
        internal static string consecutivo {
            get {
                return ResourceManager.GetString("consecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutivoActual.
        /// </summary>
        internal static string consecutivoActual {
            get {
                return ResourceManager.GetString("consecutivoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutivoInicial.
        /// </summary>
        internal static string consecutivoInicial {
            get {
                return ResourceManager.GetString("consecutivoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsecutivoPoliza.
        /// </summary>
        internal static string ConsecutivoPoliza {
            get {
                return ResourceManager.GetString("ConsecutivoPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenio.
        /// </summary>
        internal static string Convenio {
            get {
                return ResourceManager.GetString("Convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conyuge.
        /// </summary>
        internal static string conyuge {
            get {
                return ResourceManager.GetString("conyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datosObjeto.
        /// </summary>
        internal static string datosObjeto {
            get {
                return ResourceManager.GetString("datosObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datosPolizaXML.
        /// </summary>
        internal static string datosPolizaXML {
            get {
                return ResourceManager.GetString("datosPolizaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartamenoCliente.
        /// </summary>
        internal static string DepartamenoCliente {
            get {
                return ResourceManager.GetString("DepartamenoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartamentoResidencia.
        /// </summary>
        internal static string DepartamentoResidencia {
            get {
                return ResourceManager.GetString("DepartamentoResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcionEstadoPoliza.
        /// </summary>
        internal static string DescripcionEstadoPoliza {
            get {
                return ResourceManager.GetString("DescripcionEstadoPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcionPlan.
        /// </summary>
        internal static string DescripcionPlan {
            get {
                return ResourceManager.GetString("DescripcionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcionProducto.
        /// </summary>
        internal static string DescripcionProducto {
            get {
                return ResourceManager.GetString("DescripcionProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direccion.
        /// </summary>
        internal static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DireccionCliente.
        /// </summary>
        internal static string DireccionCliente {
            get {
                return ResourceManager.GetString("DireccionCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DireccionConyuge.
        /// </summary>
        internal static string DireccionConyuge {
            get {
                return ResourceManager.GetString("DireccionConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EdadMaximaConyugue.
        /// </summary>
        internal static string EdadMaximaConyugue {
            get {
                return ResourceManager.GetString("EdadMaximaConyugue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMaximaHombre.
        /// </summary>
        internal static string edadMaximaHombre {
            get {
                return ResourceManager.GetString("edadMaximaHombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMaximaMujer.
        /// </summary>
        internal static string edadMaximaMujer {
            get {
                return ResourceManager.GetString("edadMaximaMujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EdadMinimaConyugue.
        /// </summary>
        internal static string EdadMinimaConyugue {
            get {
                return ResourceManager.GetString("EdadMinimaConyugue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMinimaHombre.
        /// </summary>
        internal static string edadMinimaHombre {
            get {
                return ResourceManager.GetString("edadMinimaHombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMinimaMujer.
        /// </summary>
        internal static string edadMinimaMujer {
            get {
                return ResourceManager.GetString("edadMinimaMujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eliminado.
        /// </summary>
        internal static string Eliminado {
            get {
                return ResourceManager.GetString("Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esquema.
        /// </summary>
        internal static string esquema {
            get {
                return ResourceManager.GetString("esquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activo.
        /// </summary>
        internal static string estadoCausalNovedad {
            get {
                return ResourceManager.GetString("estadoCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activo.
        /// </summary>
        internal static string EstadoNovedad {
            get {
                return ResourceManager.GetString("EstadoNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstadoPoliza.
        /// </summary>
        internal static string EstadoPoliza {
            get {
                return ResourceManager.GetString("EstadoPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        internal static string Eventos {
            get {
                return ResourceManager.GetString("Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaAprobacion.
        /// </summary>
        internal static string fechaAprobacion {
            get {
                return ResourceManager.GetString("fechaAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaCancelacion.
        /// </summary>
        internal static string FechaCancelacion {
            get {
                return ResourceManager.GetString("FechaCancelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaCobroExitoso.
        /// </summary>
        internal static string FechaCobroExitoso {
            get {
                return ResourceManager.GetString("FechaCobroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaCreacion.
        /// </summary>
        internal static string fechaCreacion {
            get {
                return ResourceManager.GetString("fechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaCreacionEmpresa.
        /// </summary>
        internal static string fechaCreacionEmpresa {
            get {
                return ResourceManager.GetString("fechaCreacionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaNacimiento.
        /// </summary>
        internal static string fechaNacimiento {
            get {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaNacimientoCliente.
        /// </summary>
        internal static string FechaNacimientoCliente {
            get {
                return ResourceManager.GetString("FechaNacimientoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaNacimientoConyuge.
        /// </summary>
        internal static string FechaNacimientoConyuge {
            get {
                return ResourceManager.GetString("FechaNacimientoConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaSolicitud.
        /// </summary>
        internal static string FechaSolicitud {
            get {
                return ResourceManager.GetString("FechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaVencimientoTarjetaCliente.
        /// </summary>
        internal static string FechaVencimientoTarjetaCliente {
            get {
                return ResourceManager.GetString("FechaVencimientoTarjetaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero.
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneroCliente.
        /// </summary>
        internal static string GeneroCliente {
            get {
                return ResourceManager.GetString("GeneroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneroConyuge.
        /// </summary>
        internal static string GeneroConyuge {
            get {
                return ResourceManager.GetString("GeneroConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAprobacionDual.
        /// </summary>
        internal static string idAprobacionDual {
            get {
                return ResourceManager.GetString("idAprobacionDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAseguradora.
        /// </summary>
        internal static string idAseguradora {
            get {
                return ResourceManager.GetString("idAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAsesor.
        /// </summary>
        internal static string idAsesor {
            get {
                return ResourceManager.GetString("idAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCanalVenta.
        /// </summary>
        internal static string idCanalVenta {
            get {
                return ResourceManager.GetString("idCanalVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdCategoria.
        /// </summary>
        internal static string IdCategoria {
            get {
                return ResourceManager.GetString("IdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCausalNovedad.
        /// </summary>
        internal static string IdCausalNovedad {
            get {
                return ResourceManager.GetString("IdCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdCodigoPlan.
        /// </summary>
        internal static string IdCodigoPlan {
            get {
                return ResourceManager.GetString("IdCodigoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idDocumentoPoliza.
        /// </summary>
        internal static string idDocumentoPoliza {
            get {
                return ResourceManager.GetString("idDocumentoPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identificacion.
        /// </summary>
        internal static string identificacion {
            get {
                return ResourceManager.GetString("identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentificacionAseguradora.
        /// </summary>
        internal static string IdentificacionAseguradora {
            get {
                return ResourceManager.GetString("IdentificacionAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentificacionAsesor.
        /// </summary>
        internal static string IdentificacionAsesor {
            get {
                return ResourceManager.GetString("IdentificacionAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idEvento.
        /// </summary>
        internal static string idEvento {
            get {
                return ResourceManager.GetString("idEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdGenero.
        /// </summary>
        internal static string IdGenero {
            get {
                return ResourceManager.GetString("IdGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idGrupo.
        /// </summary>
        internal static string idGrupo {
            get {
                return ResourceManager.GetString("idGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idImpresionPoliza.
        /// </summary>
        internal static string idImpresionPoliza {
            get {
                return ResourceManager.GetString("idImpresionPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idIPC.
        /// </summary>
        internal static string IdIPC {
            get {
                return ResourceManager.GetString("IdIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMaestra.
        /// </summary>
        internal static string idMaestra {
            get {
                return ResourceManager.GetString("idMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMensaje.
        /// </summary>
        internal static string idMensaje {
            get {
                return ResourceManager.GetString("idMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMenu.
        /// </summary>
        internal static string idMenu {
            get {
                return ResourceManager.GetString("idMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoNovedad.
        /// </summary>
        internal static string IdNovedad {
            get {
                return ResourceManager.GetString("IdNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idOficina.
        /// </summary>
        internal static string idOficina {
            get {
                return ResourceManager.GetString("idOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPeriodicidad.
        /// </summary>
        internal static string idPeriodicidad {
            get {
                return ResourceManager.GetString("idPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPlan.
        /// </summary>
        internal static string idPlan {
            get {
                return ResourceManager.GetString("idPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idProductos.
        /// </summary>
        internal static string idProductos {
            get {
                return ResourceManager.GetString("idProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idSeguro.
        /// </summary>
        internal static string idSeguro {
            get {
                return ResourceManager.GetString("idSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idSubProductos.
        /// </summary>
        internal static string idSubProductos {
            get {
                return ResourceManager.GetString("idSubProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoDato.
        /// </summary>
        internal static string idTipoDato {
            get {
                return ResourceManager.GetString("idTipoDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoIdentificacion.
        /// </summary>
        internal static string idTipoIdentificacion {
            get {
                return ResourceManager.GetString("idTipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoMensaje.
        /// </summary>
        internal static string idTipoMensaje {
            get {
                return ResourceManager.GetString("idTipoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idVariableProducto.
        /// </summary>
        internal static string idVariableProducto {
            get {
                return ResourceManager.GetString("idVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idVariableVenta.
        /// </summary>
        internal static string idVariableVenta {
            get {
                return ResourceManager.GetString("idVariableVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idVenta.
        /// </summary>
        internal static string idVenta {
            get {
                return ResourceManager.GetString("idVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave.
        /// </summary>
        internal static string Llave {
            get {
                return ResourceManager.GetString("Llave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitud.
        /// </summary>
        internal static string longitud {
            get {
                return ResourceManager.GetString("longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximoBeneficiarios.
        /// </summary>
        internal static string MaximoBeneficiarios {
            get {
                return ResourceManager.GetString("MaximoBeneficiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MesesPeriodicidad.
        /// </summary>
        internal static string MesesPeriodicidad {
            get {
                return ResourceManager.GetString("MesesPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nacionalidad.
        /// </summary>
        internal static string nacionalidad {
            get {
                return ResourceManager.GetString("nacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NacionalidadCliente.
        /// </summary>
        internal static string NacionalidadCliente {
            get {
                return ResourceManager.GetString("NacionalidadCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewValue.
        /// </summary>
        internal static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreArchivo.
        /// </summary>
        internal static string NombreArchivo {
            get {
                return ResourceManager.GetString("NombreArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreAseguradora.
        /// </summary>
        internal static string nombreAseguradora {
            get {
                return ResourceManager.GetString("nombreAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreAsesor.
        /// </summary>
        internal static string NombreAsesor {
            get {
                return ResourceManager.GetString("NombreAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreBeneficiario.
        /// </summary>
        internal static string NombreBeneficiario {
            get {
                return ResourceManager.GetString("NombreBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreCampo.
        /// </summary>
        internal static string nombreCampo {
            get {
                return ResourceManager.GetString("nombreCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreCanalVenta.
        /// </summary>
        internal static string NombreCanalVenta {
            get {
                return ResourceManager.GetString("NombreCanalVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreNovedad.
        /// </summary>
        internal static string NombreCausalNovedad {
            get {
                return ResourceManager.GetString("NombreCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreCompletoBeneficiario.
        /// </summary>
        internal static string NombreCompletoBeneficiario {
            get {
                return ResourceManager.GetString("NombreCompletoBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreConvenio.
        /// </summary>
        internal static string nombreConvenio {
            get {
                return ResourceManager.GetString("nombreConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreGrupo.
        /// </summary>
        internal static string nombreGrupo {
            get {
                return ResourceManager.GetString("nombreGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreTipoNovedad.
        /// </summary>
        internal static string NombreNovedad {
            get {
                return ResourceManager.GetString("NombreNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreObjeto.
        /// </summary>
        internal static string nombreObjeto {
            get {
                return ResourceManager.GetString("nombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreOficina.
        /// </summary>
        internal static string NombreOficina {
            get {
                return ResourceManager.GetString("NombreOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombrePeriodicidad.
        /// </summary>
        internal static string nombrePeriodicidad {
            get {
                return ResourceManager.GetString("nombrePeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombrePlan.
        /// </summary>
        internal static string nombrePlan {
            get {
                return ResourceManager.GetString("nombrePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreProducto.
        /// </summary>
        internal static string NombreProducto {
            get {
                return ResourceManager.GetString("NombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreSeguro.
        /// </summary>
        internal static string NombreSeguro {
            get {
                return ResourceManager.GetString("NombreSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreTipoCuenta.
        /// </summary>
        internal static string NombreTipoCuenta {
            get {
                return ResourceManager.GetString("NombreTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novedad.
        /// </summary>
        internal static string Novedad {
            get {
                return ResourceManager.GetString("Novedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroCuenta.
        /// </summary>
        internal static string NumeroCuenta {
            get {
                return ResourceManager.GetString("NumeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroCuentaCliente.
        /// </summary>
        internal static string NumeroCuentaCliente {
            get {
                return ResourceManager.GetString("NumeroCuentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroIdentificacion.
        /// </summary>
        internal static string NumeroIdentificacion {
            get {
                return ResourceManager.GetString("NumeroIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroIdentificacionBeneficiario.
        /// </summary>
        internal static string NumeroIdentificacionBeneficiario {
            get {
                return ResourceManager.GetString("NumeroIdentificacionBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroIdentificacionCliente.
        /// </summary>
        internal static string NumeroIdentificacionCliente {
            get {
                return ResourceManager.GetString("NumeroIdentificacionCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroIdentificacionConyuge.
        /// </summary>
        internal static string NumeroIdentificacionConyuge {
            get {
                return ResourceManager.GetString("NumeroIdentificacionConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroMaximoSegurosPorCliente.
        /// </summary>
        internal static string NumeroMaximoSegurosPorCliente {
            get {
                return ResourceManager.GetString("NumeroMaximoSegurosPorCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroMaximoVentaSegurosPorCuentaCliente.
        /// </summary>
        internal static string NumeroMaximoVentaSegurosPorCuentaCliente {
            get {
                return ResourceManager.GetString("NumeroMaximoVentaSegurosPorCuentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroMesesPeriodicidad.
        /// </summary>
        internal static string numeroMesesPeriodicidad {
            get {
                return ResourceManager.GetString("numeroMesesPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldValue.
        /// </summary>
        internal static string OldValue {
            get {
                return ResourceManager.GetString("OldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orden.
        /// </summary>
        internal static string orden {
            get {
                return ResourceManager.GetString("orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicidad.
        /// </summary>
        internal static string Periodicidad {
            get {
                return ResourceManager.GetString("Periodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanPoliza.
        /// </summary>
        internal static string PlanPoliza {
            get {
                return ResourceManager.GetString("PlanPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plantilla.
        /// </summary>
        internal static string plantilla {
            get {
                return ResourceManager.GetString("plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PorcentajeParticipacion.
        /// </summary>
        internal static string PorcentajeParticipacion {
            get {
                return ResourceManager.GetString("PorcentajeParticipacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKeyField.
        /// </summary>
        internal static string PrimaryKeyField {
            get {
                return ResourceManager.GetString("PrimaryKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKeyValue.
        /// </summary>
        internal static string PrimaryKeyValue {
            get {
                return ResourceManager.GetString("PrimaryKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primerApellido.
        /// </summary>
        internal static string primerApellido {
            get {
                return ResourceManager.GetString("primerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimerApellidoCliente.
        /// </summary>
        internal static string PrimerApellidoCliente {
            get {
                return ResourceManager.GetString("PrimerApellidoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimerApellidoConyuge.
        /// </summary>
        internal static string PrimerApellidoConyuge {
            get {
                return ResourceManager.GetString("PrimerApellidoConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primerNombre.
        /// </summary>
        internal static string primerNombre {
            get {
                return ResourceManager.GetString("primerNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimerNombreCliente.
        /// </summary>
        internal static string PrimerNombreCliente {
            get {
                return ResourceManager.GetString("PrimerNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimerNombreConyuge.
        /// </summary>
        internal static string PrimerNombreConyuge {
            get {
                return ResourceManager.GetString("PrimerNombreConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to razonSocial.
        /// </summary>
        internal static string razonSocial {
            get {
                return ResourceManager.GetString("razonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to representanteLegal.
        /// </summary>
        internal static string representanteLegal {
            get {
                return ResourceManager.GetString("representanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundoApellido.
        /// </summary>
        internal static string segundoApellido {
            get {
                return ResourceManager.GetString("segundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegundoApellidoCliente.
        /// </summary>
        internal static string SegundoApellidoCliente {
            get {
                return ResourceManager.GetString("SegundoApellidoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegundoApellidoConyuge.
        /// </summary>
        internal static string SegundoApellidoConyuge {
            get {
                return ResourceManager.GetString("SegundoApellidoConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundoNombre.
        /// </summary>
        internal static string segundoNombre {
            get {
                return ResourceManager.GetString("segundoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegundoNombreCliente.
        /// </summary>
        internal static string SegundoNombreCliente {
            get {
                return ResourceManager.GetString("SegundoNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegundoNombreConyuge.
        /// </summary>
        internal static string SegundoNombreConyuge {
            get {
                return ResourceManager.GetString("SegundoNombreConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siguienteConsecutivo.
        /// </summary>
        internal static string siguienteConsecutivo {
            get {
                return ResourceManager.GetString("siguienteConsecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelefonoCliente.
        /// </summary>
        internal static string TelefonoCliente {
            get {
                return ResourceManager.GetString("TelefonoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelefonoConyuge.
        /// </summary>
        internal static string TelefonoConyuge {
            get {
                return ResourceManager.GetString("TelefonoConyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoCuentaCliente.
        /// </summary>
        internal static string TipoCuentaCliente {
            get {
                return ResourceManager.GetString("TipoCuentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoIdentificacion.
        /// </summary>
        internal static string TipoIdentificacion {
            get {
                return ResourceManager.GetString("TipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoIdentificacionAbreviadoCliente.
        /// </summary>
        internal static string TipoIdentificacionAbreviadoCliente {
            get {
                return ResourceManager.GetString("TipoIdentificacionAbreviadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoIdentificacionAbreviatura.
        /// </summary>
        internal static string TipoIdentificacionAbreviatura {
            get {
                return ResourceManager.GetString("TipoIdentificacionAbreviatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoIdentificacionAbreviaturaBeneficiario.
        /// </summary>
        internal static string TipoIdentificacionAbreviaturaBeneficiario {
            get {
                return ResourceManager.GetString("TipoIdentificacionAbreviaturaBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoIdentificacionDescripcionCliente.
        /// </summary>
        internal static string TipoIdentificacionDescripcionCliente {
            get {
                return ResourceManager.GetString("TipoIdentificacionDescripcionCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoNumeroIdentificacionBeneficiario.
        /// </summary>
        internal static string TipoNumeroIdentificacionBeneficiario {
            get {
                return ResourceManager.GetString("TipoNumeroIdentificacionBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltimoIPC.
        /// </summary>
        internal static string UltimoIPC {
            get {
                return ResourceManager.GetString("UltimoIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateDate.
        /// </summary>
        internal static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioAprueba.
        /// </summary>
        internal static string usuarioAprueba {
            get {
                return ResourceManager.GetString("usuarioAprueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioEnvia.
        /// </summary>
        internal static string usuarioEnvia {
            get {
                return ResourceManager.GetString("usuarioEnvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valor.
        /// </summary>
        internal static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipc.
        /// </summary>
        internal static string ValorIPC {
            get {
                return ResourceManager.GetString("ValorIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorIVA.
        /// </summary>
        internal static string ValorIVA {
            get {
                return ResourceManager.GetString("ValorIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorIvaPoliza.
        /// </summary>
        internal static string ValorIvaPoliza {
            get {
                return ResourceManager.GetString("ValorIvaPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valorMaestra.
        /// </summary>
        internal static string valorMaestra {
            get {
                return ResourceManager.GetString("valorMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorPoliza.
        /// </summary>
        internal static string ValorPoliza {
            get {
                return ResourceManager.GetString("ValorPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorPolizaSinIva.
        /// </summary>
        internal static string ValorPolizaSinIva {
            get {
                return ResourceManager.GetString("ValorPolizaSinIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorPrimaConIva.
        /// </summary>
        internal static string ValorPrimaConIva {
            get {
                return ResourceManager.GetString("ValorPrimaConIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorSinIVA.
        /// </summary>
        internal static string ValorSinIVA {
            get {
                return ResourceManager.GetString("ValorSinIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to versionDocumento.
        /// </summary>
        internal static string VersionDocumento {
            get {
                return ResourceManager.GetString("VersionDocumento", resourceCulture);
            }
        }
    }
}
