//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Repositorio.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Repositorio.Configuraciones.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La causal de novedad ya existe..
        /// </summary>
        internal static string CausalNovedadExistente {
            get {
                return ResourceManager.GetString("CausalNovedadExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Causal de Novedad se guardó exitosamente..
        /// </summary>
        internal static string CausalNovedadGuardada {
            get {
                return ResourceManager.GetString("CausalNovedadGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de la Aseguradora ya existe..
        /// </summary>
        internal static string CodigoAseguradoraExistente {
            get {
                return ResourceManager.GetString("CodigoAseguradoraExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La parametrización se actualizó satisfactoriamente.
        /// </summary>
        internal static string ControlDualActualizado {
            get {
                return ResourceManager.GetString("ControlDualActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ya esta parametrizado para esta función.
        /// </summary>
        internal static string ControlDualExiste {
            get {
                return ResourceManager.GetString("ControlDualExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La parametrización se guardó satisfactoriamente.
        /// </summary>
        internal static string ControlDualGuardado {
            get {
                return ResourceManager.GetString("ControlDualGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al momento de insertar un producto no permitido..
        /// </summary>
        internal static string ErrorInsertarProductoNoPermitido {
            get {
                return ResourceManager.GetString("ErrorInsertarProductoNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al insertar el seguro.
        /// </summary>
        internal static string ErrorInsertarSeguro {
            get {
                return ResourceManager.GetString("ErrorInsertarSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Interno {0}.
        /// </summary>
        internal static string ErrorInterno {
            get {
                return ResourceManager.GetString("ErrorInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se asoció el tipo de identificación al seguro de manera correcta.
        /// </summary>
        internal static string GuardarTipoIdentificacionSeguroExitoso {
            get {
                return ResourceManager.GetString("GuardarTipoIdentificacionSeguroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha insertado un producto no permitido.
        /// </summary>
        internal static string InsertarProductoNoPermitidoExitoso {
            get {
                return ResourceManager.GetString("InsertarProductoNoPermitidoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardó el seguro.
        /// </summary>
        internal static string InsertarSeguroExitoso {
            get {
                return ResourceManager.GetString("InsertarSeguroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Llave del mensaje ya existe..
        /// </summary>
        internal static string LlaveMensajeExistente {
            get {
                return ResourceManager.GetString("LlaveMensajeExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mensaje se guardó correctamente.
        /// </summary>
        internal static string MensajeGuardado {
            get {
                return ResourceManager.GetString("MensajeGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La novedad ya existe..
        /// </summary>
        internal static string NovedadExistente {
            get {
                return ResourceManager.GetString("NovedadExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La novedad se guardó exitosamente..
        /// </summary>
        internal static string NovedadGuardada {
            get {
                return ResourceManager.GetString("NovedadGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El permiso para el Rol ya existe..
        /// </summary>
        internal static string PermisoRolExistente {
            get {
                return ResourceManager.GetString("PermisoRolExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP005.
        /// </summary>
        internal static string PlantillaActivada {
            get {
                return ResourceManager.GetString("PlantillaActivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se almaceno exitosamente, requiere autorización dual para ser efectivo..
        /// </summary>
        internal static string RegistroTemporalAlmacenado {
            get {
                return ResourceManager.GetString("RegistroTemporalAlmacenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del Rol ya existe..
        /// </summary>
        internal static string RolExistente {
            get {
                return ResourceManager.GetString("RolExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no posee rol asociado.
        /// </summary>
        internal static string UsuarioSinRol {
            get {
                return ResourceManager.GetString("UsuarioSinRol", resourceCulture);
            }
        }
    }
}
