//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaSeguros.Repositorio.Configuraciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParametrosEntradaProcedimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametrosEntradaProcedimientos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancaSeguros.Repositorio.Configuraciones.ParametrosEntradaProcedimientos", typeof(ParametrosEntradaProcedimientos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accion.
        /// </summary>
        internal static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string Activa {
            get {
                return ResourceManager.GetString("Activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actividadEconomica.
        /// </summary>
        internal static string actividadEconomica {
            get {
                return ResourceManager.GetString("actividadEconomica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activo.
        /// </summary>
        internal static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actualizaConsecutivo.
        /// </summary>
        internal static string actualizaConsecutivo {
            get {
                return ResourceManager.GetString("actualizaConsecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @añoIPC.
        /// </summary>
        internal static string AñoIPC {
            get {
                return ResourceManager.GetString("AñoIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aseguradora.
        /// </summary>
        internal static string aseguradora {
            get {
                return ResourceManager.GetString("aseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @autoriza.
        /// </summary>
        internal static string autoriza {
            get {
                return ResourceManager.GetString("autoriza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beneficiario.
        /// </summary>
        internal static string Beneficiario {
            get {
                return ResourceManager.GetString("Beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campo.
        /// </summary>
        internal static string campo {
            get {
                return ResourceManager.GetString("campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campoLlave.
        /// </summary>
        internal static string campoLlave {
            get {
                return ResourceManager.GetString("campoLlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @camposConsulta.
        /// </summary>
        internal static string CamposArchivoPlano {
            get {
                return ResourceManager.GetString("CamposArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CamposPlantilla.
        /// </summary>
        internal static string CamposPlantilla {
            get {
                return ResourceManager.GetString("CamposPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ciudadNacimiento.
        /// </summary>
        internal static string ciudadNacimiento {
            get {
                return ResourceManager.GetString("ciudadNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigo.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoAseguradora.
        /// </summary>
        internal static string codigoAseguradora {
            get {
                return ResourceManager.GetString("codigoAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoCategoria.
        /// </summary>
        internal static string codigoCategoria {
            get {
                return ResourceManager.GetString("codigoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @codCausalNovedad.
        /// </summary>
        internal static string CodigoCausalNovedad {
            get {
                return ResourceManager.GetString("CodigoCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoConvenio.
        /// </summary>
        internal static string CodigoConvenio {
            get {
                return ResourceManager.GetString("CodigoConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @codigoFiltro.
        /// </summary>
        internal static string CodigoFiltroArchivoPlano {
            get {
                return ResourceManager.GetString("CodigoFiltroArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @codTipoNovedad.
        /// </summary>
        internal static string CodigoNovedad {
            get {
                return ResourceManager.GetString("CodigoNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoPlan.
        /// </summary>
        internal static string CodigoPlan {
            get {
                return ResourceManager.GetString("CodigoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodigoProducto.
        /// </summary>
        internal static string CodigoProducto {
            get {
                return ResourceManager.GetString("CodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoSeguro.
        /// </summary>
        internal static string codigoSeguro {
            get {
                return ResourceManager.GetString("codigoSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoSubProducto.
        /// </summary>
        internal static string CodigoSubProducto {
            get {
                return ResourceManager.GetString("CodigoSubProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigoTipoCuenta.
        /// </summary>
        internal static string codigoTipoCuenta {
            get {
                return ResourceManager.GetString("codigoTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Consecutivo.
        /// </summary>
        internal static string Consecutivo {
            get {
                return ResourceManager.GetString("Consecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutivoActual.
        /// </summary>
        internal static string consecutivoActual {
            get {
                return ResourceManager.GetString("consecutivoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutivoInicial.
        /// </summary>
        internal static string consecutivoInicial {
            get {
                return ResourceManager.GetString("consecutivoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conyuge.
        /// </summary>
        internal static string Conyuge {
            get {
                return ResourceManager.GetString("Conyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @criterioFiltro.
        /// </summary>
        internal static string CriterioFiltroArchivoPlano {
            get {
                return ResourceManager.GetString("CriterioFiltroArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos.
        /// </summary>
        internal static string Datos {
            get {
                return ResourceManager.GetString("Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datosObjeto.
        /// </summary>
        internal static string datosObjeto {
            get {
                return ResourceManager.GetString("datosObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMaximaConyugue.
        /// </summary>
        internal static string EdadMaximaConyugue {
            get {
                return ResourceManager.GetString("EdadMaximaConyugue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMaximaHombre.
        /// </summary>
        internal static string EdadMaximaHombre {
            get {
                return ResourceManager.GetString("EdadMaximaHombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMaximaMujer.
        /// </summary>
        internal static string EdadMaximaMujer {
            get {
                return ResourceManager.GetString("EdadMaximaMujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMinimaConyugue.
        /// </summary>
        internal static string EdadMinimaConyugue {
            get {
                return ResourceManager.GetString("EdadMinimaConyugue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMinimaHombre.
        /// </summary>
        internal static string EdadMinimaHombre {
            get {
                return ResourceManager.GetString("EdadMinimaHombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMinimaMujer.
        /// </summary>
        internal static string EdadMinimaMujer {
            get {
                return ResourceManager.GetString("EdadMinimaMujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Eliminado.
        /// </summary>
        internal static string Eliminado {
            get {
                return ResourceManager.GetString("Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esDual.
        /// </summary>
        internal static string esDual {
            get {
                return ResourceManager.GetString("esDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @estadoCausalNovedad.
        /// </summary>
        internal static string estadoCausalNovedad {
            get {
                return ResourceManager.GetString("estadoCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @estadoTipoNovedad.
        /// </summary>
        internal static string EstadoNovedad {
            get {
                return ResourceManager.GetString("EstadoNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to existe.
        /// </summary>
        internal static string existe {
            get {
                return ResourceManager.GetString("existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha.
        /// </summary>
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaAprobacion.
        /// </summary>
        internal static string fechaAprobacion {
            get {
                return ResourceManager.GetString("fechaAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaCreacion.
        /// </summary>
        internal static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaDeNacimientoCliente.
        /// </summary>
        internal static string fechaDeNacimientoCliente {
            get {
                return ResourceManager.GetString("fechaDeNacimientoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaFinal.
        /// </summary>
        internal static string fechaFinal {
            get {
                return ResourceManager.GetString("fechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechaFinArchivo.
        /// </summary>
        internal static string FechaFinArchivoPlano {
            get {
                return ResourceManager.GetString("FechaFinArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaInicial.
        /// </summary>
        internal static string fechaInicial {
            get {
                return ResourceManager.GetString("fechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechaInicioArchivo.
        /// </summary>
        internal static string FechaInicioArchivoPlano {
            get {
                return ResourceManager.GetString("FechaInicioArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaSolicitud.
        /// </summary>
        internal static string fechaSolicitud {
            get {
                return ResourceManager.GetString("fechaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipoProgramacionArchivo.
        /// </summary>
        internal static string FrecuenciaArchivoPlano {
            get {
                return ResourceManager.GetString("FrecuenciaArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genero.
        /// </summary>
        internal static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @horaRequest.
        /// </summary>
        internal static string horaRequest {
            get {
                return ResourceManager.GetString("horaRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @horaResponse.
        /// </summary>
        internal static string horaResponse {
            get {
                return ResourceManager.GetString("horaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAccion.
        /// </summary>
        internal static string idAccion {
            get {
                return ResourceManager.GetString("idAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAprobacionDual.
        /// </summary>
        internal static string idAprobacionDual {
            get {
                return ResourceManager.GetString("idAprobacionDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAseguradora.
        /// </summary>
        internal static string idAseguradora {
            get {
                return ResourceManager.GetString("idAseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idAsesor.
        /// </summary>
        internal static string idAsesor {
            get {
                return ResourceManager.GetString("idAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCanalVenta.
        /// </summary>
        internal static string IdCanalVenta {
            get {
                return ResourceManager.GetString("IdCanalVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdCategoria.
        /// </summary>
        internal static string IdCategoria {
            get {
                return ResourceManager.GetString("IdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idCausalNovedad.
        /// </summary>
        internal static string IdCausalNovedad {
            get {
                return ResourceManager.GetString("IdCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCodigoPlan.
        /// </summary>
        internal static string IdCodigoPlan {
            get {
                return ResourceManager.GetString("IdCodigoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idControlDual.
        /// </summary>
        internal static string IdControlDual {
            get {
                return ResourceManager.GetString("IdControlDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idConvenio.
        /// </summary>
        internal static string IdConvenio {
            get {
                return ResourceManager.GetString("IdConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idDocumentoPlantilla.
        /// </summary>
        internal static string idDocumentoPlantilla {
            get {
                return ResourceManager.GetString("idDocumentoPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idDocumentoPoliza.
        /// </summary>
        internal static string IdDocumentoPoliza {
            get {
                return ResourceManager.GetString("IdDocumentoPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identificacion.
        /// </summary>
        internal static string identificacion {
            get {
                return ResourceManager.GetString("identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idEvento.
        /// </summary>
        internal static string idEvento {
            get {
                return ResourceManager.GetString("idEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idGrupo.
        /// </summary>
        internal static string idGrupo {
            get {
                return ResourceManager.GetString("idGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMaestra.
        /// </summary>
        internal static string idMaestra {
            get {
                return ResourceManager.GetString("idMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMensaje.
        /// </summary>
        internal static string idMensaje {
            get {
                return ResourceManager.GetString("idMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idMenu.
        /// </summary>
        internal static string idMenu {
            get {
                return ResourceManager.GetString("idMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idTipoNovedad.
        /// </summary>
        internal static string IdNovedad {
            get {
                return ResourceManager.GetString("IdNovedad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @idOficina.
        /// </summary>
        internal static string idOficina {
            get {
                return ResourceManager.GetString("idOficina", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @ciudad.
        /// </summary>
        internal static string ciudad
        {
            get
            {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @activo.
        /// </summary>
        internal static string activo
        {
            get
            {
                return ResourceManager.GetString("activo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to idParametro.
        /// </summary>
        internal static string IdParametro {
            get {
                return ResourceManager.GetString("IdParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPeriodicidad.
        /// </summary>
        internal static string idPeriodicidad {
            get {
                return ResourceManager.GetString("idPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPlan.
        /// </summary>
        internal static string idPlan {
            get {
                return ResourceManager.GetString("idPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPoliza.
        /// </summary>
        internal static string idPoliza {
            get {
                return ResourceManager.GetString("idPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idProgramacion.
        /// </summary>
        internal static string IdProgramacion {
            get {
                return ResourceManager.GetString("IdProgramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idRol.
        /// </summary>
        internal static string idRol {
            get {
                return ResourceManager.GetString("idRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idSeguro.
        /// </summary>
        internal static string idSeguro {
            get {
                return ResourceManager.GetString("idSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idSubProducto.
        /// </summary>
        internal static string IdSubProducto {
            get {
                return ResourceManager.GetString("IdSubProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoDato.
        /// </summary>
        internal static string IdTipoDato {
            get {
                return ResourceManager.GetString("IdTipoDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoDeIdentificacion.
        /// </summary>
        internal static string idTipoDeIdentificacion {
            get {
                return ResourceManager.GetString("idTipoDeIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoIdentificacion.
        /// </summary>
        internal static string idTipoIdentificacion {
            get {
                return ResourceManager.GetString("idTipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipoMensaje.
        /// </summary>
        internal static string idTipoMensaje {
            get {
                return ResourceManager.GetString("idTipoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idVariableProducto.
        /// </summary>
        internal static string idVariableProducto {
            get {
                return ResourceManager.GetString("idVariableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idVariableVenta.
        /// </summary>
        internal static string idVariableVenta {
            get {
                return ResourceManager.GetString("idVariableVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idVenta.
        /// </summary>
        internal static string idVenta {
            get {
                return ResourceManager.GetString("idVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave.
        /// </summary>
        internal static string Llave {
            get {
                return ResourceManager.GetString("Llave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vP_UserName.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitud.
        /// </summary>
        internal static string longitud {
            get {
                return ResourceManager.GetString("longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximoBeneficiarios.
        /// </summary>
        internal static string MaximoBeneficiarios {
            get {
                return ResourceManager.GetString("MaximoBeneficiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreArchivo.
        /// </summary>
        internal static string NombreArchivo {
            get {
                return ResourceManager.GetString("NombreArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreArchivo.
        /// </summary>
        internal static string NombreArchivoPlano {
            get {
                return ResourceManager.GetString("NombreArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreCampo.
        /// </summary>
        internal static string nombreCampo {
            get {
                return ResourceManager.GetString("nombreCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreCausalNovedad.
        /// </summary>
        internal static string NombreCausalNovedad {
            get {
                return ResourceManager.GetString("NombreCausalNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreTipoNovedad.
        /// </summary>
        internal static string NombreNovedad {
            get {
                return ResourceManager.GetString("NombreNovedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreObjeto.
        /// </summary>
        internal static string nombreObjeto {
            get {
                return ResourceManager.GetString("nombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreTabla.
        /// </summary>
        internal static string nombreTabla {
            get {
                return ResourceManager.GetString("nombreTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuevoId.
        /// </summary>
        internal static string nuevoId {
            get {
                return ResourceManager.GetString("nuevoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuevoValor.
        /// </summary>
        internal static string nuevoValor {
            get {
                return ResourceManager.GetString("nuevoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroCuenta.
        /// </summary>
        internal static string numeroCuenta {
            get {
                return ResourceManager.GetString("numeroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroMaximoSegurosPorCliente.
        /// </summary>
        internal static string NumeroMaximoSegurosPorCliente {
            get {
                return ResourceManager.GetString("NumeroMaximoSegurosPorCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeroMaximoVentaSegurosPorCuentaCliente.
        /// </summary>
        internal static string NumeroMaximoVentaSegurosPorCuentaCliente {
            get {
                return ResourceManager.GetString("NumeroMaximoVentaSegurosPorCuentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @descripcionArchivo.
        /// </summary>
        internal static string ObjetivoArchivoPlano {
            get {
                return ResourceManager.GetString("ObjetivoArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @opcion.
        /// </summary>
        internal static string opcion {
            get {
                return ResourceManager.GetString("opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orden.
        /// </summary>
        internal static string orden {
            get {
                return ResourceManager.GetString("orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Plantilla.
        /// </summary>
        internal static string Plantilla {
            get {
                return ResourceManager.GetString("Plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlantillaXML.
        /// </summary>
        internal static string PlantillaXML {
            get {
                return ResourceManager.GetString("PlantillaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @programacion.
        /// </summary>
        internal static string ProgramacionArchivoPlano {
            get {
                return ResourceManager.GetString("ProgramacionArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @requiere.
        /// </summary>
        internal static string requiere {
            get {
                return ResourceManager.GetString("requiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rutaDestinoFTP.
        /// </summary>
        internal static string RutaFTPArchivoPlano {
            get {
                return ResourceManager.GetString("RutaFTPArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @separador.
        /// </summary>
        internal static string SeparadorArchivoPlano {
            get {
                return ResourceManager.GetString("SeparadorArchivoPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tablaPlan.
        /// </summary>
        internal static string TablaPlan {
            get {
                return ResourceManager.GetString("TablaPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tablaProductos.
        /// </summary>
        internal static string TablaProductos {
            get {
                return ResourceManager.GetString("TablaProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tablaSeguroTipoI.
        /// </summary>
        internal static string TablaSeguroTipoI {
            get {
                return ResourceManager.GetString("TablaSeguroTipoI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipo.
        /// </summary>
        internal static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipoTrans.
        /// </summary>
        internal static string tipoTransaccion {
            get {
                return ResourceManager.GetString("tipoTransaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioAprueba.
        /// </summary>
        internal static string usuarioAprueba {
            get {
                return ResourceManager.GetString("usuarioAprueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsuarioCreacion.
        /// </summary>
        internal static string UsuarioCreacion {
            get {
                return ResourceManager.GetString("UsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioEnvia.
        /// </summary>
        internal static string usuarioEnvia {
            get {
                return ResourceManager.GetString("usuarioEnvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valor.
        /// </summary>
        internal static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valorAnterior.
        /// </summary>
        internal static string valorAnterior {
            get {
                return ResourceManager.GetString("valorAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @valorIPC.
        /// </summary>
        internal static string ValorIPC {
            get {
                return ResourceManager.GetString("ValorIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valorIva.
        /// </summary>
        internal static string ValorIVA {
            get {
                return ResourceManager.GetString("ValorIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valorLlave.
        /// </summary>
        internal static string valorLlave {
            get {
                return ResourceManager.GetString("valorLlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valorSinIva.
        /// </summary>
        internal static string ValorSinIva {
            get {
                return ResourceManager.GetString("ValorSinIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionDocumento.
        /// </summary>
        internal static string VersionDocumento {
            get {
                return ResourceManager.GetString("VersionDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @xmlRequest.
        /// </summary>
        internal static string xmlRequest {
            get {
                return ResourceManager.GetString("xmlRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @xmlResponse.
        /// </summary>
        internal static string xmlResponse {
            get {
                return ResourceManager.GetString("xmlResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @tipoevento.
        /// </summary>
        internal static string tipoevento
        {
            get
            {
                return ResourceManager.GetString("tipoevento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @inicial.
        /// </summary>
        internal static string inicial
        {
            get
            {
                return ResourceManager.GetString("inicial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @inicial.
        /// </summary>
        internal static string final
        {
            get
            {
                return ResourceManager.GetString("final", resourceCulture);
            }
        }

    }
}
